import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-conclusiones',
  templateUrl: './conclusiones.component.html',
  styleUrls: ['./conclusiones.component.css']
})
export class ConclusionesComponent implements OnInit {

  subtitulo = "Consideraciones Metodológicas";
  parrafop1 = "La experiencia de ";
  parrafop2 = "Somos como somos";
  parrafop3 = " fue una oportunidad de probar la coherencia entre lo que decía, lo que hacía, con lo que sentía. Porque pareciera fácil hablar sobre el cuerpo, pero es diferente cuando se trata de exponer el propio, más cuando se tienen inconformidades con algunas partes del mismo. En ocasiones me he limitado o sentido miedo de compartir pensamientos sobre temas como el género, la sexualidad, el cuerpo, etc., y he dejado pasar comentarios retrógrados con silencios o con afirmaciones por omisión. Es muy fácil no poder respaldar las palabras y pensamientos con las acciones.";
  parrafo2 = "En este Trabajo Final de Graduación (TFG) no se empezó desde una teoría con conceptualizaciones o soluciones de otras personas. Se inicia este trabajo desde la perspectiva de la experiencia que tuve en Somos como somos, de exponer el cuerpo concreto con sus particularidades en la fotografía. Con esta experiencia aprendí que hay situaciones que no se pueden tratar si no se resuelve antes los inconvenientes personales, porque el cambio empieza en uno, al cuestionar los tópicos o los preceptos que aceptamos y utilizamos.";
  parrafo3 = "Somos como Somos no era un espacio ideal, metodológicamente hablando, para trabajar en un TFG. Era un desafío al no ser una población cautiva o un grupo consolidado. Sino era un conjunto de personas que se agruparon por el evento de una sesión de fotografías. La sesión de fotografía la vive cada persona de forma distinta con diferentes y particulares motivos. No hay una experiencia común previa que compartan las personas para conformar la identidad grupal en Somos como somos. Esto aumentó la posibilidad de incertidumbre en el trabajo. No obstante, era la población ideal para recopilar la pluralidad desde la complejidad en el tema del cuerpo.";
  parrafo4 = "La observación de las personas participantes con la que se trabajó en el TFG fue un conjunto de experiencias individuales que serían agrupadas para la reflexión, y conformarían en el grupo con las personas presentes en la primera sesión en el trabajo de campo. Las tensiones y desafíos que han sido descritas anteriormente configuran un espacio de alta incertidumbre y complejidad metodológica, que es precisamente lo sucedido en esta investigación. Al finalizar la investigación, recién se presentaba de manera más clara la singularidad de la experiencia.";
  parrafo5p1 = "Por otra parte, ";
  parrafo5p2 = "Somos como somos";
  parrafo5p3 = " significó evitar caer en la pretendida objetividad, ya que al ser parte de mi propia experiencia, no podría esconder mi posicionamiento, y pretender que no me afectaba el tiempo compartido en el trabajo grupal. En este sentido, es que se recurre a la idea de no negar el involucramiento, y se formula la noción del facilitador/participante en el proceso de investigación, cuestión que sucede cuando convergen dos circunstancias:";
  parrafo6p1 = "La primera se da cuando se obtiene información de primera mano a partir de la propia experiencia en "
  parrafo6p2 = "Somos como somos";
  parrafo6p3 = ", y a su vez, va ser diferente para cada persona. La segunda se da cuando se participa en el proyecto no como un agente externo, sino como una persona participante más en el proceso de la investigación, pues involucrada con las personas y siendo consciente que, las motivaciones varían según cada persona para participar en una sesión fotográfica. Siempre es una decisión personal participar en ";
  parrafo6p4 = "Somos como somos";
  parrafo6p5 = ". En este trabajo se seleccionó a ";
  parrafo6p6 = "Somos como somos";
  parrafo6p7 = "para aprovechar el hecho de haber participado en el proyecto y de la esencia del mismo, que significaba un proceso de reflexión personal sobre el tema del cuerpo.";
  
  subtitulo2 = "Del Tema de la Investigación a las Historias Personales";
  parrafo7 = "El tema permitía ampliar los resultados del proceso a las condiciones particulares de cada persona participante con su universo significativo, por lo que tenía que estar acompañado con indicaciones generales que ofrecía a cada persona para desarrollar su propia respuesta significativa con su material de aprendizaje. Entonces no hay respuestas buenas o malas o ideales cuando se trabaja con un tema complejo.  Siempre es más importante el proceso que permita desarrollar la confianza necesaria para que las personas puedan compartir las vivencias, en constante construcción.";
  parrafo8p1 = "Hay que recordar que la selección de los ejercicios siempre tuvo la intencionalidad de propiciar una construcción colectiva, así que funciona cualquier ejercicio que sirva para la reflexión colectiva. Lo importante es la capacidad de entretejer una propuesta con ejercicios que respeten los tiempos de aprendizaje, viviendo y sintiendo los momentos del proceso en el trabajo de campo, para adecuar la propuesta y desarrollar el tema a un nivel más profundo. En este sentido, se depende mucho del nivel de confianza entre todas las personas que participan en el proceso. De lo contrario, no van a compartir sus experiencias sentidas con detalles descriptivos de esas situaciones. La forma de implementar el tema a la investigación fue la utilización de las";
  parrafo8p2 = "historias"
  parrafo9 = "Las historias cumplen la tarea de reconstruir las vivencias con el doble propósito de ser un proceso creativo y ser la manera para registrar el proceso de investigación. La intención del registro es conceder la posibilidad de recopilar lo que pasó. Se recuerda de esa manera y se reconstruye creativamente en un espacio de reflexión personal para captar la pluralidad del esfuerzo de lo vivido, y no necesariamente la veracidad de los hechos. Si se sintió y se transmite un recuerdo en un ejercicio de historización, hay significados y depende del proceso educativo que se realice la posibilidad de comprenderlos en su contexto.";
  parrafo10 = "Todas las historias funcionan para registrar relaciones impensadas sobre el cuerpo; cuentan vivencias independientemente de su origen o enfoque que tenga la persona que investiga. El cuerpo entendido como un punto de reflexión en un tema complejo que se modifica según la sociedad y las particularidades de las personas.";
  parrafo11 = "Por lo tanto, no hay certezas absolutas sobre el mismo, sino incertidumbres particulares en constante construcción diaria de las personas, más aún en un contexto cambiante a una velocidad vertiginosa influida por la tecnología que condiciona las formas virtuales, cada vez más reales, comunes y relevantes. Desde una investigación de este tipo siempre es importante plantearse los posibles escenarios, y contar con gran cantidad de herramientas que ayuden a adaptarse, si las condiciones de trabajo cambian o si el momento lo amerita.";
  parrafo12 = "Las historias se convierten en una mediación que engloba y fomenta la creatividad en la construcción del aprendizaje elaborado individualmente. Las historias serán un intento de focalización en la interpretación, también la libertad en la que cada persona prioriza qué es lo importante y significativo de contar y registrar. En este caso, las instrucciones amplias y generales se convierten en una pieza fundamental para obtener las historias. La intención es que cada persona pudiera decidir cuál sería su enfoque individual de lo que quería contar. La forma de registrar las historias también depende de las personas: se trata de respetar un estilo propio a cada historia, cuestión que, por su estructura lineal, no se refleja solo en el texto escrito.";
  parrafo13 = "Una de las estrategias propuestas para presentar los resultados de esas historias y que no reproduzcan la linealidad de un texto es una página web, porque se puede usar elementos como videos, audios, fotos, textos e hipervínculos.  Lo anterior permite que cada persona determine la mejor manera de contar sus historias y contribuya a desarrollar un material propio. Eso es lo más importante, que el material o recurso de aprendizaje creado cumpla con el objetivo de representar a la persona, y que ésta se sienta cómoda de compartir para exponerlo en una publicación posterior, ya sea digital o física.";
  parrafo14 = "En esta investigación, el material producido no se pretendió dividir o fragmentar las historias generadas por las personas participantes con el propósito de analizarlas. Habitualmente, el análisis de la información recabada recae en el papel de la persona investigadora y conlleva el riesgo de reducir la complejidad de las historias. Por esa razón se modifica el posicionamiento del investigador por el de la persona facilitadora/participante dentro del proceso investigativo.";
  parrafo15 = "Por otro lado, un complemento a las indicaciones amplias y generales para las historias fue dar el tiempo necesario para que las personas participantes pudiesen tomar las decisiones de seleccionar una vivencia o varias, formular una narrativa propia y contar la historia como un material de aprendizaje representativo (relato escrito o dibujo). Ese tiempo resulta ser importante, en el momento de tener en cuenta en la planeación si se quiere o se persigue historias significativas o relevantes para las personas, y que se puedan usar en etapas posteriores.";
  

  subtitulo3 = "Una Historia Particular";
  parrafo16 = "Un ejemplo de este tipo de historia para trabajar, es la de Antonia que expresa una situación significativa y característica del contexto en la sociedad. Ella realizó un análisis retrospectivo de las vivencias que enmarcaba su cuerpo. Empezó con sus fotos en el proyecto. Pero poco a poco se distancia y opta por un relato particular, que es único de replicar, al representar la acumulación de sentimientos encontrados en un punto de quiebre que se replanteó a nivel personal: de lo que quiere y lo que será en el presente, y entrelazó todas esas experiencias en una historia.";
  parrafo17 = "La historia contada por Antonia se grabó en audio. Esa grabación representaba más una conversación entre amigas, cuando una de ellas necesita expresar un momento de confusión personal. Por esa razón, se consideró más importante a la persona que la investigación y que fuera ella que determinara si se podía usar en el trabajo o no.  No obstante, esta experiencia con esa historia representaba la finalidad de esta empresa educativa, cuestión que no hubiese sido posible captar con instrumentos dirigidos como entrevistas. Ya que las preguntas contienen una intencionalidad, porque las palabras por sí solas guían una forma de concebir las investigaciones y, también dependen de la interpretación de cada persona.";
  parrafo18 = "La historia sólo representa una manera de recopilar vivencias, dejando el ejercicio de pensar a las personas participantes, es de ellas la responsabilidad de enfocarse en lo que consideren significativo del tema, y a su vez, quieran contar o relatar.  Son múltiples los caminos que pueden llegar a formular y es necesario ese grado de incertidumbre si se quiere trabajar con experiencias privadas, personales, comunes y particulares.";

  subtitulo4 = "Desarrollo de Confianza y Sensibilidades";
  parrafo19p1 = "El proceso de investigación ";
  parrafo19p2 = "Somos como somos ";
  parrafo19p3 = "contó con una sesión de fotos para sensibilizar sobre el cuerpo. No obstante, lo que no preví fue la necesidad de desarrollar confianza mutua entre las personas que participaron. No hay que dar por sentado que la confianza grupal y la sensibilidad sobre el tema se construye con los mismos ejercicios o eventos o hechos que comúnmente se usan.";
  parrafo20 = "El principal inconveniente del trabajo de campo fue que no se pudo contar con la participación de las personas en varias sesiones. Esto provocó que la gente no contara con la misma información base. Después del trabajo de campo pienso que la asistencia incompleta del grupo afecta en la valoración de las dinámicas planificadas. La confianza grupal requerida para compartir las historias modificó la posibilidad de profundizar en los recuerdos o experiencias, lo cual tuvo como consecuencia que las personas participantes adoptaran un lenguaje abstracto y sin detalles sobre sus historias para así exponerse personalmente ante personas con las que no tenían confianza.";
  
  subtitulo5 ="Imprevistos en el Trabajo de Campo";
  parrafo21 = "En el trabajo de campo experimenté un cambio en mi percepción con respecto a la participación de las personas en la primera sesión, donde la gente expresa su apoyo verbal y por escrito para continuar con las siguientes fases del trabajo. No obstante, la realidad fue diferente; en un primer momento, las personas dejaron de responder a los mensajes reduciéndose el número inicial, y en un segundo momento se necesitó mucho tiempo para concretar el material con las historias que las personas deseaban compartir. Sin embargo, era un punto vital para la etapa teatral, no tiene sentido cumplir con una planeación, sin las historias como insumo del trabajo. Además, las personas participantes empezaron a no tener disponibilidad para reunirse, y a su vez, no finalizaban la constante prolongación del plazo para terminar el material con las historias.";
  parrafo22 = "Al no haber contado con todas las personas, no pude detectar que no existía confianza entre ellas sino hasta en una de las sesiones finales cuando el proceso ya estaba finalizando en la etapa de recolección de las historias. Esta importante circunstancia llevó a la cancelación de la etapa teatral para enfocar todos los esfuerzos en la recopilación del material. En esa etapa de recolección de las historias se invirtió más tiempo de lo planeado, pero resultó ser lo fundamental.";
  parrafo23 = "Las historias son la principal diferencia de este trabajo con cualquier otro que fuese realizado por una persona formada en alguna de las variables del teatro o con experiencia en el área. Ciertamente, si se quería continuar con la planeación, se hubiese necesitado realizar actividades complementarias con la finalidad de desarrollar la confianza mínima requerida, para construir ese espacio de reflexión personal y colectivo.";
  parrafo24 = "En este proceso no se utilizó una actividad integradora, introductora o sensibilizadora porque no quería que las personas sintonizaran su enfoque de trabajo sobre el cuerpo entre sí o según mi reacción como facilitador. En cierta medida, mi reacción podía influenciar en las historias. Resulta difícil lidiar con la planeación del trabajo de campo sin una actividad integradora ni la recopilación de las historias para constatar si las indicaciones fueron claras. Esto se puede percibir como otro imprevisto.";
  parrafo25 = "Sin embargo, fue intencionado limitar mi participación y brindar solamente indicaciones amplias, compartir mi historia hasta el final y en el transcurso del proceso fue que empecé a determinar qué clase de historias pueden servir para la fase de teatro. Se consideró realizar una actividad integradora para iniciar el tema, la cual no se realizó, pero se seleccionaron ejercicios, que se encuentran en la página web diseñada para este trabajo de graduación, y contienen una batería de ejercicios seleccionados para la planeación y modificaciones de actividades como talleres.";
  
  subtitulo6 = "Aprendizajes desde la Perspectiva Como Investigador";
  parrafo26 = "Una lección aprendida es que, si no se cuenta con la participación constante de todas las personas, sería mejor realizar las modificaciones requeridas, incluyendo la posibilidad de cancelar el trabajo de campo. Al no lograr la participación de todas las personas, se pierde la construcción colectiva de los significados comunes en las vivencias del trabajo.";
  parrafo27 = "Por otra parte, no hay que confundir la confianza entre las personas con la sensibilidad al tema, porque representan dos elementos requeridos en un proceso colectivo. Estos no necesariamente se dan en el mismo tiempo, ni con un mismo ejercicio o dinámica. En la planeación de procesos como éstos es importante pensar la incorporación de ejercicios que contemplen las posibilidades de trabajar tanto la confianza como la sensibilidad o ambos en situaciones grupales dependiendo del grupo y sus circunstancias.";
  parrafo28p1 = "Por lo tanto, ";
  parrafo28p2 = "Somos como somos ";
  parrafo28p3 = "resultó ser un proyecto que permite la reflexión individual y personal sobre el cuerpo que funciona como un mecanismo de sensibilización sobre el tema. Aunque en ";
  parrafo28p4 = "Somos como somos ";
  parrafo28p5 = "no se construye vivencias comunes entre las personas para reconocernos como grupo y limitando la recopilación en la información de las historias. De lo anterior, me di cuenta demasiado tarde que se requería construir una relación de confianza en el proceso y a la vez tenía la necesidad de concluir el TFG.";
  parrafo29 = "Otro aprendizaje personal es evitar hacer sesiones de trabajo si las personas no colaboran con el objetivo, ya que se vuelve desgastante tener que reiterar varias veces en lo mismo y se pierde la riqueza en la retroalimentación. Nunca se puede tener la certeza que la planificación inicial no tenga que modificarse, pero es una medida de respaldo que depende de la receptividad de las personas participantes y la habilidad de la persona facilitadora para configurar y cambiar las actividades con la finalidad de poder explorar esas relaciones imprevistas sobre el tema.";
  parrafo30 = "Es importante reconocer que las investigaciones están formuladas por las personas investigadoras, e inevitablemente las influyen, desde la selección de las palabras en el objeto de investigación, en la teoría que respalda el proceso y la metodología seleccionada. Ese enfoque también afecta a las actividades previstas de la investigación, porque la puede condicionar o guiar a una posible respuesta de las personas participantes.";
  parrafo31 = "Es un reto para desarrollar las acciones de investigación, que, a la vez, se conviertan en actividades de aprendizaje. Lo anterior exige plantearse cómo diseñar situaciones de aprendizaje en la investigación. La respuesta que encontré en el trabajo realizado es las actividades con indicaciones amplias, generales y sin especificar algún interés de la persona facilitadora. Estas indicaciones sirven como un punto inicial para la reflexión personal sobre el tema, igualmente tienen que propiciar la información funcional. Lo de funcional consiste en que evocan a múltiples vivencias.";
  parrafo32 = "No todo lo puedo hacer yo en los roles de investigador y facilitador, es decir, no se puede planear de forma perfecta. Hay que probar la propuesta en la realidad, la cual cambia la perspectiva de los elementos iniciales. Lo importante no es la planeación de una propuesta, es la aplicación de la misma y la retroalimentación del trabajo de campo. Y por esto, lo entiendo como un proceso educativo para las personas con las que se trabaja y de aprendizaje para quien investiga-facilita. Eso ayuda a corregir y ajustar los elementos de una propuesta.";
  parrafo33 = "A manera de ejemplificar lo anterior, puedo afirmar que no tenía criterios de selección para las historias, ni siquiera lo había pensado en la planeación inicial. Ciertamente que todas las historias funcionan para registrar el trabajo. No obstante, no todas las historias funcionan para usarlas en la etapa teatral y para ello, se necesitaba desarrollar los criterios."
  parrafo34li = "El primer criterio refiere a empezar con que las personas participantes estén a gusto con las vivencias seleccionadas y que el material los represente en el relato tanto como se pueda exponer el material en un documento público."
  parrafo35li = "El segundo criterio consiste en el nivel de abstracción que tiene las historias. Entre más concreta sea la descripción de las vivencias que decidió contar, resulta más factibles de usar como guion para la teatralidad. Igualmente, si se quiere usar una historia de un tercero en la fase teatral está supeditado a la aprobación de la persona autora, porque la historia se modifica y se prueban variaciones indiferentemente de la vivencia. Esto se debe que las vivencias o los recuerdos son de otra persona.";
  parrafo36li = "El tercer criterio refiere a la elección de las personas participantes para escoger las historias que quieran seguir trabajando, porque se quiere modificar algo de lo contado en la historia.";
  parrafo37 = "Hay que seguir intentándolo si se pretende desarrollar temas que tengan niveles de complejidad, más allá de las frases hechas, se convierte en fundamental identificar la conformación de un conjunto de personas que asistan a la convocatoria. Esto sirve para orientar el tipo de ejercicios o las dinámicas previas necesarias para trabajar una propuesta de investigación.";
  parrafo38 = "La formación de un grupo de trabajo es esencial para poder implementar una propuesta, es una importante lección aprendida.  Si se trabaja con un grupo conformado, se cuenta con una gran ventaja previa al iniciar un proceso grupal reflexivo. Pero no se puede partir del supuesto: que todas las personas integrantes del grupo están sintonizadas o sensibilizadas sobre el tema de igual forma.";
  parrafo39 = "Asimismo, es posible trabajar con un tema a partir de una vivencia particular y común, porque propicia la recolección variada de las historias. No obstante, las historias sin confianza no se pueden usar en la etapa teatral, ya que se requiere compartir las circunstancias de vida que permita “reconocerse como participantes en un proceso” (Montero, 2004, p.100) grupal."
  parrafo40p1 = "Entonces, la vivencia particular de ";
  parrafo40p2 = "Somos como somos ";
  parrafo40p3 = "se requiere valorar como fundamental el tiempo de trabajo para desarrollar la confianza requerida. Si se comparten las circunstancias que permiten el auto reconocerse entre las personas participantes, es fundamental no faltar a ninguna sesión.  De no lograrse, se pierde el sentido de la fase de recopilación y no se puede continuar con la fase teatral. Sin duda alguna, no importa el producto final porque para mí es más importante las personas y prefiero no exponer una reflexión retrospectiva de un recuerdo todavía abierto.";
  
  subtitulo7 = "Reflexión a Modo de Conclusión";
  parrafo41 = "En este trabajo la manera de tratar con la complejidad fue priorizar el aprendizaje para navegar dentro del proceso investigativo. Reconozco que el aprendizaje se da constante e indiferentemente si hay intención o no. Este fue el primer paso para saber que se necesita estar frecuentemente en negociación con las realidades y modificar la forma de trabajo según el aprendizaje reflexionado.";
  parrafo42 = "El punto de inicio fue partir desde la visión interseccional de las personas, desde sus múltiples posicionamientos que varían con el tiempo y las experiencias vividas. Solo se puede acceder a esa visión por la autoidentificación de cada persona y su identidad. Esto quiere decir, solo las personas pueden determinar qué es lo que reconocen como un aspecto de su identidad o no.";
  parrafo43 = "No hay ejercicios o técnicas exclusivas de autoidentificación. Esto es algo que se tiene que trabajar más para desarrollar criterios y serán mediados por las preferencias y los conocimientos de la persona investigadora, que considerará la mejor opción de trabajo para cumplir con la autoidentificación. En el presente trabajo de graduación se usó las historias para iniciar el proceso de la autoidentificación. La experiencia de las historias proporciona una posibilidad para animar a las personas que investigan atreverse a explorar otras opciones y crear sus propias formas de trabajo con una propuesta, si las opciones teóricas y metodológicas existentes no cubren las necesidades del contexto de trabajo y las expectativas personales en el ámbito profesional.";
  parrafo44 = "En ningún momento se pretende confundir lo de crear con partir desde cero. Crear es integrar los distintos niveles y aportes independientemente de su uso original, siempre y cuando esté precedido de un proceso que evalúe las propuestas existentes y de interés para conformar la propuesta. En consecuencia, se incita a un cambio en el rol de la persona investigadora y variar la forma de trabajar dependiendo de la participación con más productos ya finalizados sin modificar o analizarlos por parte de la persona investigadora.";
  parrafo45 = "Esto conlleva un riesgo al depender de la participación de las personas para realizar la investigación de temas complejos que se enfocan en el aprendizaje. Cuando el aprendizaje empieza por ser una intención implícita en el planteamiento de las actividades de aprendizaje, se reconoce el aprendizaje situado dentro del proceso constantemente en negociación con las diversas intersecciones. Es conveniente recopilar esa interseccionalidad en el tiempo en que se da la libertad a las personas participantes de crear sus historias y es posible propiciar lo variable y complejo sobre el tema de investigación. Además, la interseccionalidad fue el elemento que justificó el uso de las historias y agrupa a cualquier historia como pertinente en este trabajo.";
  parrafo46 = "Por otra parte, se necesita complementar el aprendizaje funcional con el aprendizaje eficaz, porque el primero orienta la agrupación de las diferentes aristas dentro de un tema, y, el segundo refuerza e impulsa la generación de materiales que representen o motiven a las personas con la finalidad de tener en cuenta que los insumos se utilizarán en una etapa posterior.";
  parrafo47 = "Por eso la instrucción más importante para la construcción del material fue buscar la fundamentación en “Taxonomía de Bloom en la era digital” (Churches, 2009), porque representa una actualización ante cambios y desarrollos de la tecnología en la sociedad, permite tener en cuenta la variación del comportamiento, acciones y oportunidades en el aprendizaje con las TIC.";
  parrafo48 = "Además, crear tiene la función de dar la posibilidad de integrar cuando “el proceso de aprendizaje se puede iniciar en cualquier punto” (Churches, 2009, p.1) y esa es la intensión de usar las diferentes formas en colaboración constante entre el aprendizaje y el material didáctico.";
  parrafo49 = "Igualmente, crear es una habilidad que suscita las otras habilidades cognitivas, afectivas y psicomotoras que fomentan la creatividad en una construcción individual y particular. Lo ideal es que las personas puedan oscilar libremente entre los niveles de la taxonomía (Churches, 2009) y los niveles de abstracción (Dale, 1946). El resultado en sí mismo es secundario, debido que el conocimiento con que se analiza los resultados será obsoleto con el transcurso del tiempo, lo importante es la utilización de habilidades de pensamiento para la reflexión sobre temas complejos en una primera instancia a nivel individual, luego en un proceso de construcción colectivo, puesto que da la oportunidad que las personas comprendan y se apropien de esas habilidades.";
  parrafo50 = "En este caso se seleccionó las historias y el teatro. Es posible buscar opciones de actividades que conecten distintas habilidades y dé la posibilidad de elegir el material con el nivel de abstracción, que represente significativamente a cada persona. Sobre todo, recordando que no hay actividad ideal ni preconcebida para trabajar la complejidad y la misma es un proceso constante en construcción que puede variar con el tiempo y los aportes dentro de la sociedad.";
  parrafo51 = "Trabajar con temas complejos no va salir al primer intento, se necesita desarrollar más experiencias y más aportes con puntos de vista diferentes de otras personas. El recorrido va dar las pautas requeridas para construir una propuesta o variaciones de la misma que trascienda lo ideal y lo teórico, y sea más práctica y ajustable a la realidad. Como cualquier propuesta, requiere un ajuste y adaptaciones a las condiciones del contexto. Esta fue una experiencia de aprendizaje constante durante el proceso y construir un camino propio con esta estrategia metodológica. porque resultó ser más valiosa para aplicar los conocimientos de la Licenciatura con situaciones reales que modifican las actividades de aprendizaje.";
  parrafo52 = "Ciertamente tan solo es una opción para el tratamiento de temas, problemas y circunstancias de vida complejos. Pero este trabajo es solo un punto de arranque para dar la posibilidad de imaginar y crear alternativas a los limites preconcebidos. Siempre será la mejor opción tomar el desafío de la complejidad para crear cuando “se trata de ejercitarse en un pensamiento capaz de tratar, de dialogar, de negociar con lo real” (Morin, 2005, p. 22).  Siempre existirá incertidumbre en los trabajos de investigación o académicos, solo queda navegar en la incertidumbre con estrategias “que permitan afrontar los riesgos, lo inesperado, lo incierto, y modificar su desarrollo en virtud de las informaciones adquiridas en el camino” (Morin, 1999, p.3).";

  constructor() { }

  ngOnInit() {
  }

}
