import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-antecedentes',
  templateUrl: './antecedentes.component.html',
  styleUrls: ['./antecedentes.component.css']
})
export class AntecedentesComponent implements OnInit {

  parrafo1 ="Hay dos maneras para desarrollar un trabajo final de graduación: la primera es definir previo a la etapa de formulación de la propuesta qué es lo que se quiere estudiar en el objeto de estudio o usar el estado de la cuestión o el arte para desarrollar y contrastar consignas de trabajo con la intencionalidad de afinar la propuesta. ";
  parrafo2 ="Al no tener claro el objeto de estudio, pero sí la consigna de investigar la Investigación Acción Participativa (IAP), lo que procedía era la segunda opción.  La idea inicial se centró en realizar una investigación sobre la IAP para corroborar o descartar los supuestos sobre la misma, así como evaluar de factibilidad de incorporla en la propuesta.";
  parrafo3 = "El estado de la cuestión se desarrolla enfocado a los aspectos metodológicos a partir de la IAP. Para esto se selecciona los artículos de corte metodológico que implementa en un proceso de investigación.";
  parrafo4 = "Ya que la intención es examinar cómo se utiliza la IAP, se dividió la investigación en tres áreas de interés: la primera, determinar una aproximación a la definición de la IAP aplicada; la segunda, identificar las técnicas utilizadas en la misma y la tercera área, conocer cómo se presenta los resultados en la IAP en los artículos seleccionados. Por lo tanto, IAP como un método de investigación que se caracteriza por la participación se convierte en la primera escala para la reflexión de la metodología. ";
  subtitulo1 = "Estado de la Cuestión";
  parrafo5 = "La Investigación Acción Participativa (IAP) como un principio deseable para aplicar en la metodología fue la primera idea a explorar. Por esa razón, se procedió a desarrollar el estado de la cuestión o del arte sobre la IAP a partir de una búsqueda en Redalyc.org sobre el tema. tomando en cuenta únicamente los primeros quince años del siglo XXI.";
  parrafo6 = "La Redalyc es un sistema de indización para las revistas de acceso abierto, principalmente de varios países en Latinoamérica, España, Portugal, Alemania y Polonia. De esta búsqueda resulta la preselección de los artículos vinculados a la IAP. Esta es la principal manera para presentar los resultados de una investigación, es decir es la forma de registrar la totalidad del proceso investigativo.";
  subtitulo2 = "Panorama de Investigación Acción Participativa ";
  parrafo7 = "La IAP es una frase con múltiples acepciones vinculadas, entre las que destacan: IAP como un proceso investigativo en función de un grupo o una comunidad caracterizado por ser oprimida (Balcázar, 2003b) con etapas o fases (Abad et al. 2010; Arraez, 2008), mediante ciclos iterativos (Almaguer, 2013) o en espiral (Castellano, 2014) para ajustarla hasta resolver el problema (Abad et al., 2010); aproximación teórica y metodológica para una disciplina (Balcázar, 2003b); metodología de investigación con compromiso ideológico para promover la praxis popular (Oslender, 2013); una estrategia de capacitación de manera sistemático y riguroso (González et al. 2008), o una estrategia de abordaje y acompañamiento (Anzola et al. 2015), estrategia de intervención política y científica sobre problemáticas locales, orientada por el trabajo en grupo (Obando, 2006); un modo de reorganización grupal para aprender desde su propia experiencia y resolver los problemas (Eisenberg et al. 2004); o simples evaluaciones para revisar y mejorar las prácticas (Abad et al., 2010). Con lo antes expuesto, la IAP encierra muchas interpretaciones en los intentos de aplicar una investigación de las acciones, tomando en cuenta la participación.";
  parrafo8 = "IAP se caracteriza por identificar las necesidades sentidas y expresadas de cada grupo o comunidad. El colectivo debe definir y priorizar entre sus necesidades (Koh y Castillo, 2014; Balcázar, 2003b; Almaguer, 2013). Esto se debe al carácter participativo de IAP, el cual varía la relación unilateral y exclusiva de generar conocimiento por parte de la persona investigadora. Ahora, la fórmula de generar conocimiento es colaborar (Koh y Castillo, 2014; Suchowierska y White, 2003; Abad et al., 2010; Bru y Basagoiti; S.F.; Bing et al., 2003; Almaguer, 2013; Aguilar-Idáñez, 2016) o acompañar (Anzola et al., 2015) entre personas en la toma de decisiones para el proceso.";
  parrafo9 = "La relación que revalora la función de las personas en la aplicación de IAP; se puede nombrar de distintas maneras como participantes (Abad et al., 2010; Bing et al., 2003; Koh y Castillo, 2014), miembros de una comunidad (Almaguer, 2013), o, indistintamente, en el papel de sinónimos: colaborador, usuarios y miembro del equipo investigador (Suchowierska y White; 2003). El rol de la persona investigadora pasó de un investigador experto hacia algo más dinámico y funcional para propiciar la participación. Varios autores (Valderrama, 2013; Abad et al., 2010; Anzola et al., 2015) concuerdan en desarrollar el rol de facilitador y agregar el rol de entrenador (Suchowierska y White; 2003).";
  parrafo10 = "La IAP es un proceso que trasciende el ámbito exclusivo de la investigación e incorpora otros como la educación (Balcázar, 2003a), la comunicación y la organización (Anzola et al., 2015). En el apartado de la educación se comprendió cómo descubrir el potencial de la gente para actuar y fortalecimiento de liderazgo (Balcázar, 2003b), orientar el proceso de formación profesional (Anzola et al., 2015), un aprendizaje reflexible a la formación requerida para comprender una situación social (Castellano, 2014), y aprendizaje en el propio proceso de IAP (Almaguer, 2013; Eisenberg et al., 2004; Blandón et al., 2005).";
  subtitulo3 = "Técnicas en la IAP"
  parrago11 = "En la documentación consultada se encontró la aplicación de las siguientes técnicas para la recolección de información en la IAP: diferentes formas para nombrar a la entrevista (Abad et al., 2010; Arraez, 2008): entrevista en profundidad (Abad et al., 2010; Castellano, 2014; González et al., 2008; Menéndez, 2013;), entrevista semiestructurada (Koh y Castillo, 2014), entrevista individual (Anzola et al., 2015), entrevista individual estructurada (González et al., 2008) y entrevistas informales individuales (Scandroglio y López,  2010), porque no hay suficiente información para realizar una valoración si existe o no alguna diferencia, y la entrevista con el uso de estímulos visuales: el método de sonsacamiento por foto y el autosonsacamiento por foto (Aguilar-Idáñez, 2016; Pain, 2012; Pauwels, 2015), y entrevista grupal ( Abad et al., 2010; Anzola et al., 2015; Scandroglio y López,  2010); “entrevistas exhaustivas con informantes claves, sondeos etnográficos, evaluaciones de necesidades, grupos focales, herramientas para la evaluación formativa y sumativa” (Bing et al., 2003); asamblea pública (Balcázar, 2003b); cartografía social como diagnóstico de necesidades y solución a las mismas (Quiñonez, 2011; Valderrama, 2013); observación (Abad et al., 2010) u observación participante (Arraez, 2008; Castellano, 2014; Eisenberg et al., 2004; Scandroglio y López, 2010); diario de campo (Abad et al., 2010; Castellano, 2014); test de familia (Cepeda et al. 2012); sociograma o mapa de redes y técnica DAFO –Debilidades, Amenazas, Fortalezas y Oportunidades– (Bru y Basagoiti; S.F.); bitácora grupal (Eisenberg et al., 2004); círculos de discusión (Castellano, 2014); fotovoz, fotonovela y video comunitario o video participativo (Aguilar-Idáñez, 2016; Melleiro y Gualda, 2005; Pauwels, 2015); filmvoice (Aguilar-Idáñez, 2016).";
  parrafo12 = "En el mejor de los casos, la información disponible de las técnicas es la definición conceptual sin el proceso de construcción ni ajuste en la aplicación de la IAP. Estas ocupan un segundo plano en los artículos porque se centran en validar y legitimar el planteamiento conceptual de la IAP, la relevancia del tema y los resultados.";
  parrafo13 = "La gran mayoría de estas técnicas son habituales en las investigaciones. Las que difieren de lo anterior son la asamblea pública, los círculos de discusión, dependiendo del enfoque, el sociograma o mapas de redes por su carácter participativo y la cartografía social, por su reciente auge para la aplicación en la indagación participativa y aceptación académica.";
  parrafo14 = "Por otro lado, las técnicas audiovisuales como el sonsacamiento por foto, el autosonsacamiento por foto, fotovoz, fotonovela  y video comunitario o video participativo  son de uso reciente en la investigación. Las dos primeras consisten en la incorporación de estímulos visuales /como fotos) en las entrevistas de manera que resulte menos improductivo que las entrevistas puramente verbales.";
  parrafo15 = "La diferencia entre ambos tipos radica en el rol de la persona que elige las fotos: en el autosonsacamiento, es responsabilidad del entrevistado acotado al contexto en tiempo y espacio. Esto puede o no coincidir con la investigación. En el otro caso, el rol de la persona entrevistadora/investigadora cuenta con mayor posibilidad de seleccionar de acuerdo con los objetivos de la investigación y la habilidad para estimular la entrevista. Estas modalidades de entrevistas son técnicas reconocidas para la producción de conocimiento en el ámbito académico.";
  parrafo16 = "La fotovoz y vídeo comunitario o vídeo participativo tiene una tendencia a la acción social comunitaria. Es decir, generar imágenes de las personas involucradas únicas del mundo para concientizar sobre un problema habitualmente concluyen con un evento: publicaciones, exposiciones, reuniones públicas o combinación de los anteriores (Pauwels, 2015). Más allá de la producción de conocimiento científico, según Pauwels, estas abogan a resultados esperados sin metodología ni evidencia empírica (2015). La fotovoz es un método frecuente en la investigación participativa cualitativa (Woodgate et al., 2016) que estriba en el aporte de un refuerzo visual como imagen o video para entrevistar.";
  parrafo17 = "Sin embargo, Aguilar-Idáñez considera la opción de la IAP y la sociología visual como una forma para superar esta distinción, denominada activismo científico. Este se refiere a la mezcla de técnicas visuales académicas y acción social en intervención social debido a que se complementan unas a otras (2016).";
  subtitulo4 = "Presentación de Resultados"
  parrafo18 = "Resulta conveniente reflexionar e identificar de qué manera se comunica los resultados de la investigación. Dentro del material de referencia consultado, solo 34% hace mención de los resultados. Los demás documentos priorizan elementos teóricos y síntesis del proceso.";
  parrafo19 = "La principal forma de presentar los resultados es la reconstrucción de los eventos en el trabajo de campo o retrospección discursiva escrita, dependiendo de la formulación, por parte de la persona encargada en la investigación. Estos resultados se utilizan en dos niveles: indirecta o directamente. Indirectamente consiste en un tipo de retrospección por parte de las personas que implementan la IAP, sin ningún apoyo en material recopilado en el transcurso de la misma. Directamente estriba en una reconstrucción a partir del material recopilado por medio de las técnicas antes mencionadas para investigar.";
  parrafo20 = "Sobre lo anterior, existe una excepción para presentar resultados de otras formas. Quiñonez (2011) menciona las posibilidades de los mapas mentales al dibujar la realidad. Estos mapas facilitan plasmar las estructuras de las relaciones, y, a la vez, considerarlo como un lenguaje compartido en sí mismo para la configuración del territorio. También, Aguilar-Idáñez (2016) tiene un apartado de filmografía, constituido por tres vídeos como productos del trabajo.";
  parrafo21 = "Por lo tanto, la manera de presentar los resultados es un tema menor dentro de la IAP y en términos generales de la investigación. Al ser el lenguaje escrito la forma predominante detectada para presentar los resultados de una investigación, se necesita explorar otras maneras.";
  parrafo22 = "En este estado de cosas, según la documentación revisada, se puede determinar que la IAP es una corriente dentro de la lógica intrínseca  en ciencias sociales. Sin duda alguna, la IAP innova en cuestiones teóricas, pero predominan el uso de las mismas técnicas en la investigación general y el lenguaje escrito para presentar resultados.";
  parrafo23 = "De esta manera, resulta difícil denotar una diferencia entre la documentación de las investigaciones que utilizan a la IAP y las otras investigaciones que no. El término de IAP varía mucho entre las investigaciones prácticas y los apartados metodológicos son pocos desarrollados. Además, las técnicas no determinan a la labor en la IAP, pero aportarían más elementos para discutir sobre la misma. Por último, se pierde la riqueza del proceso cuando se registra exclusivamente con un informe escrito para alguna publicación académica.";
  parrafo24 = "Lo anterior generó confusión para determinar en qué se ha convertido la IAP en la palestra de la investigación actual y si se puede utilizar en este proceso sin una reflexión previa. Esto provocó, en algún momento, considerar descartar la idea de usar la IAP como el gran marco de referencia porque abarca más allá del tiempo dado para el proceso de Trabajo Final de Graduación (TFG). En este intento por aclarar este gran tópico de la IAP, se encontraron algunos indicios que orientaban la búsqueda para este trabajo y fueron los siguientes:";
  subtitulo5 = "Referentes para esta Investigación";
  parrafo25 = "Existen cinco referentes en la IAP para este trabajo: Patricia Trujillo López (2011) con su trabajo: Investigación Acción, Género y Teatro del Oprimido; Tomás Motos Teruel (2010) con su trabajo Teatro Imagen: Expresión corporal y dramatización; Alejandra Astrid León Cedeño (2010) con su trabajo Danzando la Psicología Social Comunitaria: revisitando la IAP a partir de un curso de danza en una asociación cultural de barrio; Andrea Calsamiglia Madurga y Jenny Cubells Serra (2016) con su trabajo El potencial del teatro foro como herramienta de investigación; y una opción visual y Cigdem Esin (2017) con Telling Stories in Pictures: Constituting Processual and Relational Narratives in Research With Young British Muslim Women in East London.";
  parrafo26 = "Trujillo (2011) intenta realizar un vínculo entre investigación y teatro del oprimido. No obstante, este intento es un debate de carácter teórico, retomando muchos pasajes de Augusto Boal.";
  parrafo27 = "En el referente de Motos (2010), el autor describe el procedimiento y ejercicios del teatro imagen como una herramienta de intervención educativa. Además, valora la dramatización del teatro imagen como un lenguaje total porque genera nuevos ambientes de aprendizaje a partir de “analizar experiencias vividas negativamente y asumirlas para tratar de modificar sus efectos y buscar alternativas de solución” (Motos, 2010, p. 72). Al final, la presentación de resultados integra algunas fotos, fruto de la aplicación del mismo.";
  parrafo28 = "León (2010) realiza avances significativos a nivel tanto epistemológico como metodológico. La mejora epistemológica consiste en reformular la concepción de objetividad a partir del conocimiento situado. El nivel metodológico consta de valorar la danza como una técnica narrativa para investigar integralmente, capaz de unificar los conocimientos de la danza, la comunidad y las vidas de las personas participantes; pero este punto queda en una simple justificación sin profundizar en la experiencia de la aplicación de la misma. Además, hace una crítica al modelo clásico de IAP conformado por tres fases rígidas y de orden lineal: planeación, ejecución y evaluación, porque no siempre ocurre de este modo en la IAP.";
  parrafo29 = "Calsamiglia y Cubells (2016) visibilizan el aporte teórico de la epistemología feminista. Las autoras parten del conocimiento situado e interseccional en el teatro foro desde la investigación cualitativa. Pero este aporte queda desfasado porque se menciona y no se vincula con la propuesta de teatro foro.";
  parrafo30 = "Por último, Esin (2017) utiliza el método multimodal, el cual consiste en el análisis de las narrativas procesales entre las narrativas visuales, las narrativas verbales y la interacción en el proceso de investigación. Las narrativas visuales radicaron en talleres de artes para representar las autobiográficas visuales, es decir, contar sus vidas con la silueta del cuerpo. Con respecto a las narrativas verbales, versa en entrevistas para construir co-narrativas. La interacción refiere a identidad, posicionamiento y recursos personales, culturales, sociales y políticos que configuran la investigación.  Las participantes estaban constituidas por un grupo de cinco mujeres jóvenes británicas de origen musulmán entre 12 y 14 años. Al final, se trata de que las participantes cuenten sus historias y se utilizan las imágenes para constar de apoyo visual al artículo.";
  parrafo31 = "Hasta el momento, existen vestigios para aplicar técnicas diferentes a la tradición investigativa de las ciencias sociales (observación participante, entrevistas individuales o grupales) en la IAP y otras disciplinas como en la antropología visual y sociología visual, con técnicas de narrativas visuales y apoyo de multimedia para investigar. Además, existe la multiplicación dramática como una opción, que puede ser una metodología en sí misma. El problema es que no se tiene el acceso al libro de Hernán Kesselman y Eduardo Pavlovsky con el mismo nombre. Debido a esto, se requiere profundizar sobre la multiplicación dramática como una propuesta metodológica por medio de una entrevista. Según lo antes expuesto, estos esfuerzos son las primeras piezas de un rompecabezas para pensar en diferentes latitudes."

  constructor() { }

  ngOnInit() {
  }

}
