import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-resultadocampo',
  templateUrl: './resultadocampo.component.html',
  styleUrls: ['./resultadocampo.component.css']
})
export class ResultadocampoComponent implements OnInit {
  currentOrientation = 'horizontal';
  tituloAniretake = "Aniretake"
  parrafoaniretake = "Tenía 15 años, cuando vi el cuerpo desnudo de otro hombre por primera vez. Ya me había acostumbrado a la idea: en el camerino de futbol era un espacio grupal, en donde existía la posibilidad de quitarse la ropa a la vista de otros hombres, pero conservando la ropa interior (calzoncillo o bóxer). En los deportes individuales que había estado como natación y atletismo, no necesitaba una preparación colectiva, siempre era cambiarse la ropa en privado e individual. Ese día estaba preparándome  para jugar un partido de futbol. Cuando de pronto, un hombre irrumpió en el camerino vociferando improperios, calculo que la edad rondaba entre 18 y 20 años. Lo que no esperaba durante su berrinche, empieza desprenderse de toda la ropa en la puerta y se desplaza a las duchas en una distancia de 6 metros. El cuerpo del fulano era esbelto, pero lo que me llamo la atención, era ver un cuerpo sin ningún pelo corporal, es decir el tipo se rasuraba el cuerpo. Esto me hizo recordar el estereotipo que los pelos se relacionaban con lo sucio y lo feo. En el sentido que los cuerpos no eran deseados con los pelos. Este estereotipo era un tema recurrente e instado por mis familiares de una edad similar y compañeros de equipo y colegio. Aunque, fue la primera vez que veía un cuerpo sin pelos corporales, antes solo  había visto las piernas rasuradas y los comentarios de los genitales rasurados.";
  parrafoaniretake2 = "En otra ocasión, estaba en una fila para una revisión previa a un partido de futbol. Cuando escucho un bullicio y presto atención de qué se trataba la discusión, era sobre quien tenía los testículos más grandes. Al momento de la comparación un hombre perdió, para no darse por menos el tipo contestó: ustedes saben, los hombres que tienen los testículos pequeños, es porque tienen el pene grande, en un tono de alarde y fanfarroneo. ";
  parrafoaniretake3= "En otra oportunidad, me acuerdo que llegue a un grupo de compañeros en el colegio, cuando un compañero dice que el tamaño del pene importa y entre más grande mejor. Otro compañero sintió la necesidad de hacer una salvedad con un comentario: eso estaba mal, pero era peor, si el pene estaba circuncidado por no ser normal y le daba asco, porque le parecía un hongo.";     
  
  tituloAntonia= "Antonia"
  historiaAntonia = "Un recuerdo de Antonia";
  parrafoAntonia = "A los 27  años disfrutando de la vida universidad y siguiendo entre relaciones sentimentales algo conflictivas, en un momento de libertad intermitente e independencia, Antonia decide mostrar su cuerpo de una manera natural, sin pensamientos perversos, queriendo verse físicamente, lo cual es algo complicado estando rodeada de tantos fetiches sociales.";
  parrafoAntonia2 = "Una experiencia única e inolvidable, no solo por el hecho de desnudarse frente a personas, sino también por el hecho de que el sentimiento que se produjo durante ese momento, mostro ser de soledad, tristeza, miedo, vergüenza, caos y nebulosas mentales de su vida, vida que en ese momento era marcado por su independencia, y aunque alegre por haber salido de su casa y buscar su propia vida,  realmente estaba enredada en una relación sentimental , eso entre estar y no estar en pareja, a lo que ella le llamó libertad intermitente.";
  parrafoAntonia3 = "En fin, en ese círculo de intermitencia, en espacios de convivencia con el chico, decide mostrar aquellas fotografías hermosas, donde naturalmente se muestra esa chica: morena, de cabello arrepentido, ojos achinados, pechos puntiagudos y caídos, contextura ósea particular: espalda ancha,  piernas bonitas, en fin, una chica bonita a su parecer.";
  parrafoAntonia4 = " Su alma de verdad  triste, confundida y con miedo, fue más  marcado cuando Antonia muestra a su pareja  las fotografías de aquella sesión,  la reacción: el chico reacciona totalmente en desacuerdo con  aquellas fotos, él no  mencionó palabras normales a la ocasión, no  dijo: ¡que lindas fotos! O algo por el estilo a la ocasión: ¡te dio vergüenza desnudarte? O mejor aún ¿Cómo te sentiste?, las palabras fueron :¿que estabas pensado para hacer eso?, quien manipulo a Antonia para hacerlo?, aquella escena fue suficiente, para que el miedo ganara y la fotografías siempre estuvieran dentro de un sobre, solo siendo vista por ella, ¡claro! en momentos de soledad.";
  parrafoAntonia5 = "Sin embargo, aquella situación viene a calar en el presente de Antonia, cuando hace un par de meses  decide no continuar con la relación sentimental, y piensa: con la razón de sentirse con  miedo, sola,  autoestima algo anulada, ella actuó dócilmente y tímidamente aquella ocasión, cuando el chico reacciono de la manera irrespetuosa contra ella al ver las fotografías, es un recuerdo que afirma la decisión de no seguir con esa relación,  y hacer un cambio en su vida, que a sus 33 años, si hoy alguna persona ve esas fotografías, definitivamente sabrá que responder o simplemente no contestar, sabiendo que no necesita nada más que seguir confiando en ella misma.";
  
  tituloGeorgeanella = "Georgeanella"
  parrafoGeorgeanella ="Desde mi infancia el tema del cuerpo, mi cuerpo, ha tenido peso, nos basamos en cómo nos sentimos y como nos vemos, es y será parte del día a día, y con el paso de los años aceptamos tantas cosas y otras nos cuesta más.";
  parrafoGeorgeanella2 = "Escuchar los  relatos de mujeres (pocos hombres) que están a dieta, que no se sentían cómodas con cierta ropa, que hacen chistes un poco crueles, pienso yo, de su propia imagen, que no les gusta las dimensiones de su cuerpo en general, es común de escuchar, y por qué no, de decirlo también.";
  parrafoGeorgeanella3 = "En  lo personal, desde la infancia, considero que tuve algunas repercusiones en cuanto la aceptación de mi cuerpo, mis hermanos mayores, me decían gorda, de seguro para molestar, y hasta la fecha me dicen, pero ahora le tengo cariño a ese gorda, pero en la infancia me preocupaba y le dije a mi mamá que solo comería 17 frijoles y no sé cuánto de arroz, y si literal debía contarlos, pero carne y ensalada sí. Entonces a temprana edad me preocupaba ser gorda, primera barrera mental llena de estereotipos. Luego la segunda barrera fueron las pecas de mi rostro, las cuales por muchos años, fueron un dolor de cabeza, en cuanto a los apodos de niños, y por lo tanto me aplique en el rostro todo lo que decían que funcionaba para quitar las pecas, y puedo decir que no, las pecas no se quitan con nada, solo que ahora me encantan.";
  parrafoGeorgeanella4 = "Por lo que de la infancia a la adolescencia hay una marcada línea de aceptación, en la infancia no te abruma tanto pero en la adolescencia sí, hay una presión de la sociedad a ciertos parámetros, los cuales no entiendes pero quieres encajar, y si cuesta muchísimo quererse y aceptarse, pero esta no es la mejor etapa para estos das palabras. Hay mucho conflicto en tu cabeza, quieres verte bien y además adelantas tu madurez como a la fuerza, y creo que esto se debe a la presión social, ideales de belleza que te asombran en los diferentes medios, ligados a que según los medios superando estos ideales, llegaras al éxito.";
  parrafoGeorgeanella5 = "Hay momento, personas, decisiones y circunstancias que te marcan, y hacen que la valoración de tu cuerpo como ser único y especial. Poder conocer el cuerpo, sus cambios, y la importancia de estar aquí es vital para desarrollarnos. Superar estas barreras mentales, los estereotipos de todos los días, la presión social ante los “lindo y lo ideal”. Una circunstancia, el embarazo, te transforma y en todo sentido. Momentos muchos, un mirarse al espejo y sonreír, sentirse bien, sentirse feliz. Personas y momentos, participar en el proyecto somos como somos, me hizo ver de una manera tan maravillosa los cuerpos desnudos, todos diferentes, todos únicos, colores de todas gamas, cicatrices con historias, cabellos de todas formas, rostros, miradas profundas, y en esos momentos aparece lo mágico, cuando puedes entender que todos somos diferentes pero todos somos únicos, ahí donde ningún estereotipo te puede juzgar, no hay envoltura. La aceptación es increíble, y lo plasman las imágenes donde no mienten, donde la comodidad de ser tú mismo, es fundamental.";
  parrafoGeorgeanella6 = "Quererse y aceptarse, es un trabajo diario, es el mejor proyecto de vida, es poder romper las limitaciones mentales, y dejar que esto no confunda nuestros pensamientos, es valorar nuestra genética, nuestra familia, nuestra historia.";
  tituloLaMedusa = "La Medusa"
  historiaLaMedusa = `Tema: Experiencia sobre la construcción del cuerpo`;
  parrafoLaMedusa = "La desnudez es una forma valiosa de expresión, con ella comunicamos y enfrentamos con todo nuestro ser, la naturalidad  de nuestro cuerpo. El cuerpo muestra lo que somos y rompe las barreras de enfrentarnos a vernos más allá de lo físico.";
  parrafoLaMedusa2 = " Desde mi experiencia con la fotografía y cuerpo, he podido establecer conexiones entre lo que siento, el amor propio y el paso del tiempo. Me he tomado fotografías desnuda desde mis “veintes” y he podido apreciar más allá de lo visual, lo que pensaba, el cambio de mi cuerpo y  valorar quien soy.";
  parrafoLaMedusa3 = "Cuando nos desnudamos frente a la cámara, rompemos esquemas. De alguna manera cambiamos el pensamiento y nos abrimos a un mar de oportunidades, a visualizarnos naturales y sinceramente humanos.";
  parrafoLaMedusa4 = "Cuando he posado desnuda me he visto feliz, atractiva, soñadora. Cuando he sido la fotógrafa, de desnudos, he procurado desde el respeto, capturar la esencia y belleza del cuerpo humano de los otros."
  parrafoLaMedusa5 = " Sé que para algunos desnudarnos genera pudor, y de alguna forma depende de la confianza con quien estás. Intimar con alguien a ese nivel es una ventaja, que no es fácil de encontrar para todos, pero al menos desde mi experiencia y al creer en el arte como expresión, la desnudez ha sido un enfoque que abarca lo sentimental, los retos, el amor y un paso atrevido."
  
  tituloLunadeSanJorge ="Luna de San Jorge"

  tituloNigromante = "Nigromante"
  subtitulo = "Miedo"
  texto="Durante la sesión me subí desnudo a un árbol en la playa. El árbol estaba seco y lleno de espinas, me costaba moverme entre las ramas. Esto me recordaba los miedos de infancia, atávicos; el sol, la arena caliente y el cielo…. solo incrementaban el sentimiento."
  subtitulob = "Cuando era niño"
  textob = "Cuando estaba posando vinieron a mi mente los recuerdos de la infancia cuando, con solo 5 o 6 años,  me iba para el potrero en El Alto a quitarme la ropa y pasear, con todo el morbo de ser descubierto. Eso me generaba mucho placer (ahora sé que un niño también es un ser sexuado y sexual). El aire era frio y se sentía agradable sobre el cuerpo desnudo. En el momento de las fotos estos recuerdos agradables me impulsaron a continuar, a no negarme el gusto de hacerlo."
  subtituloc = "Ante otra persona"
  textoc = "Tuve que luchar internamente contra el morbo de desnudarme ante otra persona con otro objetivo que no fuera sexual, algo muy extraño para mí. A pesar de que en mi familia el desnudo no era un tabú, tampoco éramos gente que compartía la desnudez en forma natural, sin malicia. Mama llamaba al pene “la cosita” o “la polla”. Una vez el viejo me dijo que no me prestaba el paño para secarme porque “yo lo uso y me lo paso por las verijas”… Años después entendí el concepto de verijas e igual me pareció raro, durante mucho tiempo, que no me hubiera prestado la bendita toalla. Finalmente entendí que no estaba haciendo nada extraño, nada malo, nada prohibido, estaba haciendo algo hermoso, que mi cuerpo podía ser  aceptable también para mí. "
  subtitulod ="Mis relaciones"
  textod= "Afirmo que la sesión fue una especie de liberación final, ya que recientemente acababa de terminar una relación matrimonial de muchos años. Estaba empezando a acostumbrarme a vivir solo, a despegarme de dependencias enfermizas y obligaciones auto impuestas. Quitarme la ropa y dejar que Marcia me fotografiara me terminó de confirmar que estaba retomando mi vida como individuo, como persona… ya no como padre dedicado o marido protector."
  subtituloe= "La quinta dimensión"
  textoe="Durante el viaje de Heredia a Puerto Cortez establecí una conexión sensible con la fotógrafa, que eliminó totalmente mis temores.  Me encantó la seriedad con que toma su trabajo y la cantidad de temas en las que había coincidencias. Cuando finalmente llegamos al pueblo entramos en la quinta dimensión: pasamos por una parte del camino lleno de árboles y perdimos la noción del tiempo y el espacio, creo que al fondo el mar nos arrullaba con los cantos de las ballenas. Ella me generó mucha confianza."
  


  constructor() { }

  ngOnInit() {
  }

}
