import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-marcoteorico',
  templateUrl: './marcoteorico.component.html',
  styleUrls: ['./marcoteorico.component.css']
})
export class MarcoteoricoComponent implements OnInit {

  parrafo = "Cada persona es una intersección de interrelaciones con otras personas, simultáneamente, en múltiples posicionamientos en sus escenarios y roles sociales cambiantes que conforman una identidad particular desde nuestras experiencias, y de las estructuras sociales que organizan nuestras vidas (Platero, 2012). No obstante, esta conceptualización de la identidad a través de la interseccionalidad, no hay que entenderla como un montón de casillas que convergen en una persona, sino como un proceso que fluye entre y sobre los aspectos de cada persona para la conformación de la identidad (Ferrari, 2018). Esta interseccionalidad se refleja entre nuestras prácticas cotidianas.";
  parrafo2 = "Las experiencias son el contexto propio y variable de cada persona, influenciado por organizadores sociales que pueden o no jerarquizar de diferentes maneras a las experiencias. Estos organizadores consisten en construcciones “que normativizan las vidas… en momentos históricos y sociedades determinadas” (Platero, 2012, p. 22), se refleja en formas desiguales o discriminatorias en las relaciones entre las personas. Además, las experiencias están constituidas indivisible e integralmente entre los conocimientos, las rutinas y las actividades de diferentes índoles en el día a día, esto genera las vivencias.";
  parrafo3 = "Dentro de nuestras experiencias, hay imágenes de situaciones con personas que están cargadas de significados. Estas imágenes, presentes en nuestras acciones, puede “que nos impida hacer lo que queremos o nos obliga a hacer lo que no queremos: dejamos de realizar nuestro deseo para cumplir” (Boal, 2004, p. 217) el deseo de un agente externo. Dicho agente puede ser los medios de comunicación, las redes sociales, la familia, la policía, las iglesias, las personas que componen el ámbito laboral y sentimental o el grupo de amistades, etc. La influencia de tales agentes tiene un rango variable: desde una forma sutil hasta una forma explícita, con la finalidad de internalizar y naturalizar los patrones socialmente aceptados como una especie de fantasma. Boal (2004) indicaba que las cabezas son una especie de refugio para albergar este tipo de imágenes.";
  parrafo4 = "Por esta razón, se parte de los acontecimientos más banales, ya que estos están cargados con los principios y los mecanismos organizadores de la sociedad. En otros términos, “los grandes temas se inscriben en los problemas personales” (Boal, 2004, p. 61). Entonces, actuar es una opción interesante para trabajar con las vivencias de las personas participantes. Según Boal, hay una posibilidad de vincular los componentes terapéutico y pedagógico en dicho proceso, debido a la configuración de un proceso para reflexionar y comprender, cuando se reviven las vivencias.";
  parrafo5 = "Por consiguiente, se entiende por actuar como un laboratorio  social con los ejercicios teatrales, principalmente provenientes del teatro del oprimido, para ensayar en el presente y asimismo, recordar las vivencias, imaginar e implementar mundos posibles. Se entiende al teatro como estrategia metodológica, el cual es un “procedimiento heurístico que permite tomar decisiones en condiciones específicas” (Latorre y Seco, 2013, p. 19) relacionado con el aprendizaje.";
  parrafo6 = "Ahora bien, se distinguen tres formas de aprendizaje entre la amplia gama existente: situado (Lave y Wenger, 1991; Seely et al., 1989), funcional (Penzo et al., 2010) y eficaz (Dale, 1946). Estos aprendizajes son tres aspectos importantes para desarrollar la idea de trabajar con vivencias. El situado rescata el aprendizaje que se produce todos los días. Funcional y eficaz remiten a la reflexión de qué tipo de aprendizaje inicial es el que se plantea en este proceso educativo.";
  imagen = "./assets/img/marco teorico/aprendizaje-ideal.png";
  fuente = "Elaboración propia, 2020"
  parrafo7 = "El aprendizaje situado consiste en una renegociación personal y constante a lo largo de la vida; la cual interactúa, entreteje y valora una situación entre las experiencias Por experiencias se refiere al conocimiento, saber y sentido común producto de diferentes fuentes y aplicable a las prácticas; las interrelaciones con el entorno, las personas con los papeles sociales asumidos o no y, nuestras prácticas sociales como actividades y rutinas de diferente índole en el uso cotidiano (Lave y Wenger, 1991; Seely et al., 1989).";
  parrafo8 = "El aprendizaje funcional remite a la intensión de evocar a las situaciones múltiples de los hechos reales en las actividades de aprendizaje. Estas actividades procuran que sirva para aprender, promueva la toma de decisiones propias entre las personas participantes y el principal insumo es la práctica o la situación real (Penzo et al., 2010). Este es el aprendizaje que se utiliza para realizar el cambio del enfoque en el teatro a partir de situaciones hipotéticas o ideales a vivencias de las personas participantes como el guion de los ejercicios teatrales.";
  parrafo9 = "El aprendizaje entendido como eficaz ocurre cuando convergen tres condiciones: tener una motivación, tener claro lo que se va a aprender y saber qué uso práctico tendrá en la vida diaria con el propósito de superar la verbalización, o el mecanismo de la mera memorización. Este término infiere al uso meramente verbal de las palabras, el cual las desvincula de las experiencias sensoriales, motoras, reales y directas que generaron a las mismas.  El aprendizaje es un proceso interactivo constante entre lo concreto y lo abstracto para comprender nuestras experiencias y desarrollar nuestras propias generalizaciones (Dale, 1946).";
  parrafo10 = "Igualmente, Dale (1946) proporciona una herramienta de análisis de los materiales pedagógico audiovisuales como lo es el cono de la experiencia. Este dispositivo pictórico plantea que hay 10 diferentes niveles de abstracción que se intercalan y se combinan en el aprendizaje.";
  imagen2 = "./assets/img/propuesta/dale.png";
  fuente2p1 = "Elaboración propia a partir de";
  fuente2p2 = "Dale";
  fuente2p3 = ", 1946, p. 39.";
  enlace = "./assets/img/imagenesvarias/conodalevo.png";
  parrafo11 = "Los dos niveles en la base del cono son los que están directamente relacionado con las experiencias concretas y que implican crear experiencias directas y artificiales. Cuando se incrementa el nivel, incrementa la abstracción porque se distancia de la experiencia concreta. En este segundo bloque se relaciona con las diferentes formas de observar.";
  parrafo12 = "En el caso de la participación dramática se subdivide: participar en una dramatización o simplemente ser una persona observadora, porque son dos formas diferentes de aprender. Los dos niveles en la punta del cono son las formas de aprendizaje más abstractas, generalizables e independientes de las experiencias: se trata de los símbolos visuales y verbales (Dale, 1946). Según lo antes expuesto, el diagrama refuerza la idea de utilizar el teatro y buscar una forma de recopilar las experiencias directas.";
  parrafa13 = "Entonces, una forma de integrar las vivencias y el aprendizaje eficaz es la autodefinición de Hill. La articulación entre lo que se hace y se piensa se ayudan entre sí, a nivel individual. Además, puede servir para caracterizar las experiencias e ideas como un colectivo de trabajo. Con la salvedad, “las experiencias comunes pueden predisponer a desarrollar una conciencia…” -colectiva- “… distinta, no garantizan que tal conciencia se desarrolle en todas las…” –personas- “…ni que sea articulada como tal por el grupo” (Hill, 2012, p. 106), porque los puntos de vista son cambiantes, por la variación y la trascendencia de las experiencias. Para eso hay que valorarlos como un reto común el cual puede promover similitudes en pensamientos y acciones que conlleve a formular saberes colectivos o no.";
  parrafo14 = "Aún cuando Hill reconoce la existencia de cuestiones centrales, esto no significa que las personas respondan de la misma manera. Es decir, las diferencias producen conocimiento experiencial, distintivo y reacciones individuales a esas cuestiones centrales, propio de un punto de vista heterogéneo. Porque el cambio en el pensamiento puede generar acciones diferentes, hasta ese momento, y las experiencias pueden modificar la conciencia.";
  parrafo15 = "La autodefinición refleja nuestras conexiones con las prácticas en el pensamiento y el actuar que influyen en nuestra vida cotidiana. De ahí la importancia que cada persona se conozca a sí misma, y que conlleve a definirse a partir de utilizar el conocimiento cotidiano (2012) para la creación de materiales audiovisuales de cada persona en el proceso de aprendizaje.";
  parrafo16 = "En síntesis, el aprendizaje funcional resalta la importancia de partir de los hechos reales de la práctica y como se maneja en el trabajo: las vivencias autodefinidas de las personas, y con el aprendizaje eficaz la posibilidad de elegir el tipo de material de aprendizaje que se desarrolle en el trabajo con las historias. El nexo entre ambos es promover la creatividad entre las personas que participen en el proceso. Pues, el aprendizaje ideal es utilizar las vivencias de las personas participantes y pertinentes al tema.";
  parrafo17 = "La reflexión del aprendizaje conlleva a pensar los elementos desde lo funcional y lo eficaz tanto en las actividades como en los materiales. La forma de diseñar es el vínculo entre el material (contenido) y las actividades de aprendizaje con las historias, las cuales son la clave para recopilar los recuerdos o vivencias de las prácticas o actividades relacionadas con el tema en este trabajo: el cuerpo. El material representa una oportunidad de personalizar el contenido y la forma de comunicar para cada persona participante. Al mismo tiempo, propiciar la creatividad en qué y cómo lo quiera contar."

  constructor() { }

  ngOnInit() {
  }

}
