import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-revisiondoc',
  templateUrl: './revisiondoc.component.html',
  styleUrls: ['./revisiondoc.component.css']
})
export class RevisiondocComponent implements OnInit {



  parrafo = "La intención de analizar las entrevistas es buscar el modo de “¿Cómo puedo continuar el diálogo con el texto que he escrito junto con el entrevistado?” (Kvale, 1996, p. 283). Kvale (1996) lo cree posible si hay un dialogo continuo con las transcripciones de las entrevistas para desarrollar esas zonas de posibles significados y así desplegar un horizonte con una conversación.";
  subtitulo = "Los Resultados de las Entrevistas Presentadas de Manera Narrativa";
  parrafo2 = "En vez de usar una propuesta tal cual, se recopilan todos los elementos relevantes de las entrevistas para incorporarlos en la propuesta. Esto la recomendación de Quirós (2017) sobre el Teatro del Oprimido (T.O.) de usar diferentes técnicas de varias áreas y modificarlas hasta apropiarse de las mismas. La apropiación empieza a partir de desarrollar un estilo. Para eso lo primero es determinar los estilos de cada una de las expertas para desarrollar mi propio estilo.";
  nota = "Hace referencia que no importa que se utilicen las mismas actividades o incluso la misma planeación. La forma de trabajar de cada persona es distinta al depender del enfoque, cualidades particulares y las experiencias personales para conformar el estilo.";
  subtitulo2 = "Estilo de Nancy Rebecca Banard";
  parrafo3 = "El estilo de Nancy es trabajar desde el orden simbólico a través del mito, el cuento o leyenda con imágenes y relatos como una forma de desprenderse del orden cotidiano y lo nombrable. Multiplicación Dramática (M.D) consiste en proyectarse sin miedo para aumentar esa posibilidad de perderse con el resultado temático.";
  parrafo4 = "La finalidad de trabajar con relatos fantásticos como mitos, leyendas y cuentos es que representen energías arquetípicas con símbolos e imágenes de las que no escapa ningún grupo humano (familia, nacimiento, muerte, pelea, lucha) en vez de usar una herida que es conocida por las personas. La intención es bajar las resistencias y acceder a través de diferentes inteligencias.";
  parrafo5 = "Sin embargo, no hay que confundir estar perdido (en términos que la persona no sabe el resultado del tema) con no saber aplicar el método del dispositivo de M.D.  Es decir,";
  cita = "yo voy a trabajar con el orden de lo simbólico, con el arquetipo, con el mito, con el cuento. Yo sí tengo que saber: qué, cómo y para qué. El resultado es lo que yo no sé. Porque el grupo es el que hace la nomenclatura. De igual manera, yo puedo hacer o reproducir el taller en diferentes grupos y lo que sale es absolutamente otra cosa. (Banard, 2016, p. 7).";
  parrafo6 = "En síntesis, es una cuestión de estilo propio que trabaja con herramientas y recursos de lo simbólico para acercar el tema. Esta tiene tres fases: el caldeamiento, la acción y el compartir – la última depende de la capacidad de la persona coordinadora para orientar e integrar lo que pasó en la sesión. Nancy se queda con lo simbólico al usar la M.D. más que “las escenas de la vida real”. No se puede ampliar la información sobre las fases, porque la entrevista hace referencia primordialmente a los eventos ocurridos en el taller de Multiplicación Dramática: 'Arquetipos' del 27 de febrero del 2016 y no hay disponible material complementario sobre la M. D. Resulta difícil desarrollar generalidades solo de un caso cuando “hay que perderse” (Banard, 2016, p. 3) como regla principal de la M D.";
  parrafo7 = "Además, es imposible usar la M.D. en este trabajo porque se necesita una preparación previa o entrenamiento sobre la misma. Algo que no es factible para usar en el TFG. Cualquier pretensión de querer usar la M. D. resultaría ser un acto de irresponsabilidad hacia las personas que participen en el proceso de TFG e irrespeto a las personas que lean este trabajo. La entrevista sobre M.D. deja en evidencia la profundidad y la complejidad de la misma.";
  parrafo8 = "A pesar de mi deseo de utilizar la M.D. tal cual, algo similar sucedió con T.O. y I.A.P en el inicio de este trabajo, pero con razones diferentes. Por esta razón, la posibilidad se desestima al no tener la adecuada preparación ni se cuenta con la comprensión de las características requeridas en la M.D. Por ejemplo, si se quiere multiplicar, hay que perderse; y trabajar con el orden de lo simbólico a través de los mitos, cuentos y leyendas que representan las energías arquetípicas con símbolos e imágenes prácticamente universales para usar la propuesta. Pues “la multiplicación es un acto que no es sino siendo, no se puede hablar de ella, hay que ponerla en escena” (Banard, 2016, p.12).";
  subtitulo3 = "Estilo de Olinda Bravo";
  parrafo9 = "En el caso del estilo de Olinda no tiene una propuesta tan estructurada como la M.D., pero tiene experiencia de facilitar grupos de mujeres. Entre las técnicas que Olinda menciona que tiene conocimiento: los dibujos que comparan cómo era en el pasado y cómo soy en el presente, los cuentos de género, el análisis de canciones, los grupos de autoayuda, las constelaciones familiares y las historias de vida.";
  parrafo10 = "El estilo de Olinda coincide con el estilo de Nancy en la utilización de los cuentos y los dibujos para promover el análisis y profundizar las heridas de sus experiencias pasadas. Estas son expresadas a partir de la auto identificación con una parte del cuento o la comparación de los dibujos. Ella rescata la potencialidad que tiene como “un simple cuento toca un montón de emociones” (Bravo, 2016, p. 2).";
  parrafo11 = "Ciertamente Olinda no lo plantea en los mismos términos de Nancy. Pero se puede hacer la inferencia que las dos buscan disminuir la resistencia de las personas cuando intentan promover la participación de forma indirecta a las heridas experimentadas.";
  parrafo12 = "En el estilo de Olinda es fundamental desarrollar la confianza para facilitar al grupo. Señala que se consigue con el tiempo para escuchar a las personas. Eso quiere decir que no hay que dar recetas ni dar consejos o culpabilizar ni estigmatizar, porque no hay una manera estándar para todas las personas o dejarse llevar por los prejuicios. Cuando se da receta o consejos se desencantan a las personas, pues se pierde la relación de confianza. “Tal vez lo que para otra mujer funcionó para ella no va a funcionar. Entonces, allí vienen los desencantos de esas relaciones de confianza… me dijo que hiciera esto y fue peor. Mejor estaba como estaba antes” (Bravo, 2016, p. 7).";
  parrafo13 = "Además, hay una segunda acepción del término confianza que depende de la preparación de las historias de vida como una técnica terapéutica, y la empatía con la persona que le aplica la misma. Ya que requiere sentir confianza para compartir los recuerdos. En conclusión, “la persona tiene que confiar en vos. Primero, tiene que tener una confianza, esa persona en vos, saber que no va pasar nada malo, que no estás haciendo eso por cuestionarla, sino que es para sanar” (Bravo, 2016, p. 6).";
  parrafo14 = "De igual manera, advierte que la persona que facilita al grupo no está aislada. Solo por el hecho de escuchar puede afectar tanto a las personas que facilitan como al grupo, porque son los cuerpos los que reaccionan a los relatos y a las situaciones.";
  parrafo15 = "Otra característica en el estilo de Olinda es la auto facilitación en el grupo de autoayuda. Este grupo no tiene un tema, se maneja en la mínima expresión la participación de Olinda. Las que facilitan las sesiones son las mujeres de acuerdo las necesidades de cada una de ellas. Tal como ocurre en la siguiente descripción:";
  cita2 = "Yo llego hoy, hacemos la introducción y comienzan, alguna dice: “Yo quiero compartir hoy lo que me pasó como cuando era chiquita..., La otra dice: “Ay sí, fíjate, pero conmigo fue diferente, porque fue así.” Y así se pasa las dos horas. Y la próxima sesión lo mismo, “Hola, ¿cómo están?”";
  cita3 = "Entonces, tal vez llegue alguien en crisis, se deja que llore, ya cuando se calma, las otras compañeras le dan contención, la abrazan, le dicen que no está sola, que aquí están todas ellas para apoyarla, lo que le está pasando todas lo han pasado. Entonces, si ella decide contar, cuenta, sino no. Sino contenciones, masajitos y todas las compañeras se le acercan, pero hasta que haya pasado su llanto. Ahí, si en esa sesión ella lloró dos horas, pues, dos horas y todas aguardamos silencio. Esa fue la sesión, que ella llorara. Si se calma y dice que quiere compartir.";
  cita4 = "Entonces, ya comienza a contar. Y como te dije, algunas se pierden tres o cuatro meses y vuelven aparecer a la quinta sesión y ya dice porque no habían llegado, si quieren o sino no. Por eso es abierto ese espacio (Bravo, 2016, p. 9-10).";
  parrafo16 = "Al mismo tiempo, cuando la persona facilitadora observa a las personas participantes en las actividades del grupo, proporciona un tiempo para evaluar si una persona está lista para trabajar con los ejercicios terapéuticos o no. Entre lo que hay que observar son las aptitudes que muestran la cara, si las personas participan, las opiniones sobre el tema, le afectan o no y propone iniciativas o se dispersan. Estas serían señales para evaluar. Por ejemplo:";
  cita5 = "una va viendo, cuando nos reunimos con los grupos, ahí vos miras, conforme vas tocando temas, vos vas analizando quien sentís ya dio el siguiente paso y quienes todavía no. Se mira, se mira, se mira, porque mientras, vos facilitas el tema. Vos miras a quien lo golpea más el tema, a quien se le aguada el ojo, a quien se te pierde, se te pierde. El tema está, pero ella está en quién sabe dónde. Entonces, vos como facilitador de un grupo tienes que ser observador (Bravo, 2016, p. 3).";
  parrafo17 = "Por otro lado, la reflexión de Nancy sobre el tema en la M. D. se puede usar con las constelaciones familiares. Esta es una de esas técnicas en las que se aplica. Pero no se sabe que puede surgir de la aplicación porque depende de la nomenclatura del grupo.";
  parrafo18 = "Además, hay que perderse para revivir los recuerdos y propiciar la creatividad en las respuestas. Existe la posibilidad que emanen vivencias inesperadas, por lo que se trabaja hasta que la persona considere que el proceso cerró o sea suficiente. Es una conclusión que se puede utilizar para cualquier técnica y a cualquier propuesta que evoca a la dimensión terapéutica.";
  parrafo19 = "A diferencia de Nancy con la M. D., que se puede aplicar a cualquier persona solo con la preparación en la sesión, Olinda resalta la importancia que se necesita de una preparación previa para utilizar la constelación familiar. Pero es una pauta recomendada para cualquier otro elemento terapéutico en una técnica debido al riesgo de dejar a la persona en una situación peor y sin la preparación adecuada.";
  parrafo20 = "Siempre hay que dejar en claro la existencia de ese riesgo. Para la prevención del riesgo hay que trabajar solo con las personas que quieran dejar o soltar, porque consiste en mover los sentimientos de recuerdos que afloran, hasta puede suceder que surjan situaciones inesperadas que pretendíamos ya olvidadas.";
  parrafo21 = "Según lo antes expuesto en términos de Olinda:";
  cita6 = "Las constelaciones son más fuertes, son sentimientos que vamos a mover. Entonces, la persona tiene que estar dispuesta a pasar ese proceso. Si yo no estoy lista. No. Porque te voy a dejar en una situación peor. Es algo con lo que yo ya quiera romper, soltar eso. Pero si yo no lo quiero soltar, no puedo participar en ninguna constelación. Porque lo que voy a hacer es mover recuerdos, sentimientos. Y si estaba mal, voy a quedar peor, porque no quiero soltar. Entonces, primeros se les habla a las personas, se les explica que vamos a mover sentimientos, en que consiste las constelaciones, es un grupo que vamos a participar, que nos vamos a encontrar con cosas que nosotras pensamos que hemos olvidado, pero que están ahí adentro y que, por medio de esa constelación, esas cosas van aflorando, que vamos a enfrentar a personas que nosotras, no pudimos expresar y que en esa constelación nosotras vamos a expresar. Vamos a sacar y la vamos a enfrentar, y al enfrentarte yo a vos, yo estoy sana, porque en el momento que yo te enfrento y te digo: Adrián, porque me hiciste esto. Yo estoy sacando todo eso y estoy sanando. Entonces, se les preguntan si ellas se sienten que ya pueden pasar a ese proceso (Bravo, 2016, p. 3).";
  parrafo22 = "Todo depende del grupo y hay que trabajar para considerar si se puede usar los ejercicios terapéuticos con las personas o no, porque se requiere un nivel de preparación. Hay principios complementarios para usar la dimensión terapéutica de un ejercicio: no hacer daño y cerrar ciclos."; 
  parrafo23 = "Hay similitudes entre las constelaciones familiares con otros ejercicios terapéuticos que se pueden usar en la propuesta. La recomendación es que después de utilizar una técnica con matices terapéuticos, se continúa con un ejercicio para liberar esa energía que se cargó con la técnica terapéutica, o por lo menos utilizar algún ejercicio para relajar. En el caso de Olinda utiliza ejercicios de respiración. Lo que hay que hacer es buscar y seleccionar ejercicios de relajación para incorporar a mi propio estilo.";
  subtitulo4 = "Estilo de Andreína en T.O.";
  parrafo24 = "Andreína es la primera persona de las entrevistadas que menciona la utilización de juegos y la dimensión lúdica para despertar la creatividad entre las personas. El estilo de Andreína prefiere el uso de los caldeamientos dinámicos que propicien lo lúdico y lo sugerente desde la creatividad y menos mental. Ella estructura su estilo a partir de la apropiación del Teatro del Oprimido, técnicas de Clown y de la Improvisación Teatral en las siguientes tres fases:";
  cita7 = "Siempre cómo qué se busca, primero generar un ambiente de confianza, luego un ambiente de disposición corporal para que el cuerpo esté dispuesto. Entonces, técnicas que respondan más como calentar o dejar en disposición corporal. Luego, ya técnicas de contenido; esas técnicas que sacan como más información. Entonces, piénsalo desde ahí, las técnicas que generan confianza son como: verse a los ojos y tocar sus cuerpos, así como ir reconociéndose (Quirós, 2017, p.7).";
  parrafo25 = "Una de las principales inquietudes fue entender la concepción de imagen que se utiliza en T.O. porque hay varias áreas del teatro – como T.O., Psicodrama, Teatro Comunitario, etc., con diferente connotación. En T.O., la imagen es una herramienta que puede comunicar temas específicos. Al final, es cualquier cosa que se proponga en la construcción grupal. “Cuando se trabaja en las comunidades, es eso: propongan una imagen con un movimiento y un sonido, puede ser cualquiera, algunas imágenes pueden ser más sugerentes que otras” (Quirós, 2017, p.1-2). Andreína afirma que las primeras imágenes dicen algo, estas representan cuestiones más impuestas y no nacen de cada persona.";
  parrafo26 = "La otra gran inquietud era saber los criterios para seleccionar los ejercicios. Pero la respuesta de apropiarse de los ejercicios conlleva a un callejón sin salida, ya que hace referencia directa a la experiencia y la sistematización en el libro: Juegos para Teatro-foro-Clown (Colectiva Respiral, 2017), el cual presenta la propuesta, esbozan los principios y describen los ejercicios ya seleccionados.";
  parrafo27 = "Después de analizar el libro del Arcoíris del deseo por Boal (2004) y la entrevista sobre T.O. no tenía muy claro los criterios para seleccionar los ejercicios de la propuesta entre la gran cantidad ejercicios de Boal. El principal resultado indirecto de la entrevista sobre T.O. fue poder participar en un taller de Arcoíris del deseo el domingo 15 de julio del 2017. El facilitador me indica que la clave para seleccionar los ejercicios es la clasificación de los ejercicios en otro libro de Boal: Juego de actores y no actores (para más detalles, revisar la página web: http://localhost:4200/metodologia/(segundorouter:resultadosiniciales) donde se encuentra la clasificación completa).";
  parrafo28 = "A partir de ese libro es que se cuenta con una orientación y el criterio de apropiarme de algunos ejercicios de las cinco categorías con sus respectivas series. Ya que es imposible usar todos los ejercicios como una especie de maratón, lo mejor sería construir la propuesta con la apropiación de los ejercicios que he experimentado para crear mi propio estilo.";
  parrafo29 = "Las tres propuestas de las expertas resaltan la necesidad de preparación previa para obtener respuestas sugerentes, o por lo menos que trasciendan de las respuestas simbólicas, comunes, socialmente aceptadas y depende de la persona facilitadora y del interés del grupo. Ya que las primeras imágenes que surgen por lo general son simbólicas y abstractas, hay que despertar lenguajes más sensibles.";
  parrafo30 = "Además, hay muchas formas de plantearse las limitaciones del lenguaje verbal a través de las preguntas o indicaciones indirectas al tema de interés. En el caso de Olinda, hay dos ejemplos. El primero es usar los dibujos como una manera alternativa de reflexionar a nivel individual. Aunque las mujeres no hablen directamente sobre ellas. El segundo es usar los cuentos de género para identificarse y superar las respuestas directas del presunto bienestar. En términos de Olinda:";
  cita8 = "una cosa así tan simple, toca sentimientos y comenzar a explorar todito eso. Si yo hubiera dicho, contemos cómo nos sentimos, cómo sentimos, que nos ha marcado nuestra vida o cómo estamos viviendo nuestra situación en el hogar. Ellas te contestan que están bien. Usted siente que la respetan, usted siente que le dan su espacio. Cómo siente la relación entre su esposo y usted. Ellas te dicen: bueno ahí normal. Pero con el cuentecito. Entonces, comienza todas, hay una mayor participación de ellas (Bravo, 2016, p. 1).";
  parrafo31 = "A continuación, Nancy hace su propio cuestionamiento a las preguntas directas, lo ejemplifica con su estilo desde el orden simbólico:";
  cita9 = "Empiezo a preguntar: si fueras el coordinador, si fueras la loba que canta la canción. Cuál es la canción que cantas. Entonces, se unen en grupos y empiezan a ver cuál es la canción que yo canto… ahí ya no me quedo en si soy un coordinador tímido o fuerte o temeroso. Ya empieza a trabajar a nivel simbólico, qué es lo que yo canto, qué es lo que yo hago, cómo es que recurro una criatura de carne, piel y hueso. Sí. Me empiezo a salir del borde. Es decir, el contorno del mapa que yo conozco como soy coordinador que me sé muy bien la teoría, que he practicado mucho. Me salgo de ahí. ¿Cuál es la canción que cantas? (Banard, 2016, p. 6).";
  parrafo32 = "Entre los hallazgos del componente de metodología se encontraron los siguientes aspectos teóricos prácticos:";
  parrafo33 = "Un requisito antes de usar una propuesta es la preparación previa en las personas para trabajar."
  parrafo34 = "“El coordinador tiene que saber, finalmente, cual es el tema que viene a trabajar, cómo lo va a trabajar, que es lo que va hacer. De lo que no sabe es el resultado” (Banard, 2016, p. 7). Esto es una salvedad que hace Nancy, se debe de tener claro el plan de acción independientemente que la propuesta en sí requiera perderse para multiplicar. Además, en el encuadre se establecen las reglas o los principios para el trabajo.";
  parrafo35 = "Para trabajar con personas es fundamental desarrollar la confianza. Olinda menciona que la confianza se desarrolla a partir de escuchar a las personas, y, por el otro, Andreína considera que las técnicas generan la confianza requerida para trabajar grupalmente. Lo anterior solo son dos ejemplos para desarrollar la confianza.";
  parrafo36 = "Si se quiere extenderse de las respuestas dadas y los lugares comunes. Entonces tanto la preparación previa como la confianza constituyen lo esencial para acceder a un nivel de trabajo que profundice a las primeras impresiones.";
  parrafo37 = "Es posible trabajar de forma indirecta los temas. El tiempo que se dispone para trabajar marca una diferencia en la selección de las técnicas. Cuando se han experimentado heridas con el tema elegido y al no contar con tiempo, se puede desarrollar con el orden de lo simbólico: cuento y mito u leyenda. En el caso contrario que se cuente con tiempo, se puede escuchar a las personas y complementar con otras actividades.";
  subtitulo5 = "Los Hallazgos del Componente de Teatralidad";
  parrafo38 = "Se encontraron los siguientes aspectos teóricos prácticos:";
  parrafo39 = "El primer hallazgo del componente de teatralidad es detectar los dos principales criterios de selección para el caldeamiento: estimular los sentidos y clasificación de ejercicios, los cuales serán desarrollados en el encuadre. A pesar que se encuentran los criterios de selección y agregando la gran cantidad de ejercicios, la faena de selección se convierte en una elección subjetiva. Por lo tanto, la persona que facilita el trabajo grupal tiene la libertad de elegir los ejercicios que considera adecuados para poner en práctica hasta apropiarse de los mismos. Este proceso de apropiación refiere al segundo hallazgo.";
  parrafo40 = "Al mismo tiempo, no hay una manera única de garantizar el éxito en la selección de los ejercicios en una propuesta. Lo único que queda es arriesgar y seleccionar los ejercicios que ayuden a darle forma a la propuesta acorde con mis capacidades y mis limitaciones en función de ponerme en los zapatos de las personas que puedan participar en el proceso de TFG.";
  parrafo41 = "No obstante, surge el inconveniente que, después de la revisión de los ejercicios teatrales, se detecta que los mismos forman parte de propuestas específicas con finalidades distintas para este trabajo (Teatro del Oprimido y la formación profesional en teatro). Los ejercicios teatrales están pensados con principios implícitos que caracterizan cada libro y entrevista, y a su vez, responden a necesidades particulares del contexto.";
  parrafo42 = "Al tener en cuenta la finalidad de los ejercicios teatrales, se requiere utilizar ejercicios complementarios para darle contenido a la propuesta en una sección de la página web que recopile tanto los ejercicios teatrales como los ejercicios complementarios. Pues, la finalidad es proponer una metodología a partir del aprendizaje. Es decir, preguntarse constantemente cómo se aprende en este proceso y priorizar el aprendizaje ante los otros criterios como metodológicos, disciplinarios, académicos e investigativos.";
  parrafo43 = "En síntesis, no hay un camino fácil para crear un estilo de trabajo. Hay muchas opciones de estilos, pero no se puede acceder solo con entrevistas. También se requiere experimentar esos ejercicios o dinámicas o actividades. Es decir, lo que cuenta al final es apropiarse de los elementos que concuerdan a la visión de mundo y la intención de lo que quiero transmitir con un estilo propio.";
  fuente = "Elaboración propia, 2020.";


  constructor() { }

  ngOnInit() {
  }

}
