import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-problema',
  templateUrl: './problema.component.html',
  styleUrls: ['./problema.component.css']
})
export class ProblemaComponent implements OnInit {
  
  imagen = "./assets/img/imagenesvarias/posicion.png";
  imagen2 = "./assets/img/imagenesvarias/topico.png";
  fuente = "Elaboración propia, 2020.";
  fuente2 = "Man meets Woman. 2014. Single focus / Multitasking. © Yang Liu Design/ TASCHEN.";

  tititulo = "Condiciones Previas del Problema";
  parrafo = "“Todo sirve” es una frase de Paul Feyerabend (1986) que remite a la necesidad de no someterse a ciertas reglas obvias para ampliar el conocimiento. Sin importar la regla obvia por más fundamental o necesaria, hay dos circunstancias que resultan recomendables para desatender a las mismas. La primera de estas estriba que la argumentación perdió el aspecto prometedor que convencía. Esta se convierte en un formalismo cuando los argumentos aparentan surtir efecto, principalmente, por la repetición y la aceptación en el ámbito académico.";
  parrafo2 = "La segunda circunstancia consiste en el aprendizaje que modela las formas de pensar con conclusiones predeterminadas. La frase “Todo sirve” resulta ser un proceso de comparar la gama de alternativas y decidir por qué se “necesita gente adaptable e imaginativa, no imitadores rígidos de patrones ‘establecidos’ de comportamiento” (Feyerabend, 1986, p. 206) para investigar la complejidad.";
  parrafo3 = "Por esa razón, se examina algunas cuestiones iniciales de la investigación como  principios organizadores en la práctica investigativa: (preconfiguración de la realidad en cualitativo, cualitativo y mixto y el uso del lenguaje escrito y verbal), los privilegios de las personas investigadoras (papel de sujeto iniciador y productor de la investigación) y la existencia de un estancamiento de las técnicas en la investigación que predominan (encuesta, entrevista, observación, historia de vida, grupos de discusión) y de otras técnicas que no son tan reconocidas por la comunidad académica en Ciencias Sociales. Estos principios, privilegios y técnicas han cambiado con el transcurso del tiempo y han colaborado a la aceptación de la investigación cualitativa (Anadón, 2007).";
  parrafo4 = "Este trabajo es un ejercicio de pensar en posibilidades más allá de los bordes mentales para integrar los avances tecnológicos en la investigación, acorde a las contingencias de un contexto que se modifica a pasos agigantados y que, a su vez, cambia las dinámicas de la sociedad. Siempre que no se convierta en una exigencia ni requisito. La tecnología no es plastilina para usar en todos los casos, ni mucho menos una garantía de lograr un éxito. Es decir, no en todas las investigaciones o las temáticas se pueden usar sin una reflexión previa. Al final, es solo una opción más que aporta al proceso lúdico y anecdótico a la investigación.";
  parrafo5 = "En este sentido, una forma de ejercitar y reflexionar sobre la investigación sería con la metáfora de Mario Zúñiga: “Las vacas no son como son, son como queramos pintarlas” (Zúñiga, 2010, p.16). Cuando en las situaciones, los hechos y los principios se utilizan como respuestas dadas, inamovibles, normalizadas y naturalizadas sin alternativas porque se cree que no puede representar de otra manera, es el momento de cuestionar y reflexionar sobre esas prácticas.";
  parrafo6 = "Ahora bien, esta metáfora de las vacas representa una manera de cuestionar esos tópicos, la cual consiste en investigar preguntando por medio del lenguaje exclusivamente escrito y verbal con una aproximación metodológica que privilegia los significados de los signos para establecer un conocimiento objetivo. La otra es aprender haciendo, o más bien, el cómo aplicar el aprender haciendo para superar las respuestas socialmente esperadas. Por último, está lo micro social, es decir, cómo estudiar las formas sutiles para trabajar. Un ejemplo de esto sería los micromachismos.";
  parrafo7 = "Según Artega (2012), los tópicos son los lugares verbales y comunes entre las personas de un grupo determinado que se expresan con frases hechas, prefabricadas, códigos estandarizados de conducta y de expresión o clichés dispuestos para uso de cada persona. Con el uso de los tópicos como un cemento de la naturalidad, la familiaridad y la complacencia en las relaciones cotidianas, se pretenden encontrarse con la mayoría, “el ahorro de esfuerzo explicativo cuando entramos en comunicación, que sería muy fatigosa como tuviéramos que dar razones de cuanto decimos y sin reposar en lo que todos damos por sabido” (Artega, 2012, p.3).";
  parrafo8 = "En estas frases prefabricadas manifiestan los pensamientos de los otros propios de una sociedad, de manera anónima, impersonal y automática, porque no se ha pensado o producido por nosotros mismos. Los tópicos impuestos delatan las creencias y prejuicios colectivos de la sociedad si se usan como una forma para evitar pensar. Cada persona es responsable de la apropiación de los mismos y dejarlos circular (Artega, 2012).";
  parrafo9 = "En síntesis, los tópicos son parte de una serie de principios que orienta el cuestionamiento durante este texto y la construcción de una propuesta. Algunos de estos son los privilegios de superioridad, el mansplaining (término tomado de Los hombres me explican cosas de Rebecca Solnit) y el extractivismo cognitivo. De ahí que la investigación requiere reflexionar sobre sí misma, y diseñar un acercamiento metodológico desde la educación no formal en los espacios cotidianos y comunes como conversaciones de pares virtuales o físicas, así como la utilización de redes sociales para dar contenidos a las realidades complejas con infinidad de colores.";
  parrafo10 = "La creación de conocimiento académico se fundamenta en la ruptura de cualquier conocimiento que no aplique los estándares científicos (Puentes, 2015). En este afán por la ruptura, se promueve la fragmentación de la realidad para procurar el cumplimiento de los requisitos en una disciplina y provoca desvalorizar el conocimiento cotidiano. Por este motivo, se sigue planteando puntos de vista en términos de dualismos interminables.";
  parrafo11 = "Además, se mantiene la necesidad de utilizar los principios característicos de la objetividad: abstracción, generalización y problematización, entendidas el primero como la ausencia de las condiciones iniciales de tiempo y espacio; el segundo, la posibilidad de aplicar conocimiento, teoría o técnica en cualquier lugar; y el tercero como la construcción a priori de un problema acorde a los cánones de la disciplina.";
  parrafo12 = "La rigurosidad relacionada al diseño de investigación radica en usarla de forma genérica. Según Hernández, Fernández y Baptista (2014) y Batthyány y Cabrera (2011), dicha rigurosidad está constituida por los siguientes elementos constantes: planteamiento del problema con objetivos y preguntas generadoras. marco teórico con las variables o los constructos que conllevan a la operacionalización o la medición de las mismas y metodología. En este último elemento sólo existen tres tipos de enfoques: cuantitativo, el cual radica en asignar números a las propiedades de la realidad y medirlas (Canales, 2006); cualitativo, que prioriza conocer los significados y los códigos que se reproducen por medio del lenguaje escrito, verbal o simbólico en la sociedad (Canales, 2006); y mixto, que integra los dos enfoques anteriores en tres estrategias (complementaria, combinación y triangulación) (Batthyány y Cabrera, 2011)."
  parrafo13 ="Tanto la problematización como el marco teórico determinan el tipo de abordaje y selección de las técnicas. Muchos componentes del diseño de investigación se definen a priori. Sin embargo, la realidad es más compleja o contraria al planteamiento. Es decir, existen situaciones no esperadas o inconvenientes en la planificación que desajusten el diseño. No obstante, se prioriza el nivel de coherencia y claridad en el texto entre el qué, el cómo y el para qué de la investigación (Toro y Parra, 2010), más que la práctica de la misma.";
  parrafo14 = "Dentro de las prácticas dominantes y las convenciones en el ámbito académico, se puede resaltar el lenguaje de carácter técnico y despersonalizado (Maletta, 2009) y las técnicas habituales para investigar, por ejemplo: fuentes primarias, fuentes secundarias, encuesta, entrevista, observación, historia de vida, grupos de discusión (Batthyány y Cabrera, 2011). El uso de este tipo de lenguaje promueve el distanciamiento del “sujeto conocedor que se está por conocer de todos y de todo en interés de poder sin trabas” (Haraway, 1995, p. 324). A su vez, contribuye a la construcción de pensamiento académico objetivo, es decir, a representaciones abstractas y generalizables.";
  parrafo15 = "Dichas convenciones no son un posicionamiento inocente: la objetividad legitima la diferenciación de las formas de conocer y la fragmentación de la realidad. Esto implica una mirada desde un posicionamiento no marcado, con la pretensión de crear conocimiento desinteresado, el cual está inscrito en el desdoblamiento del sujeto y el objeto de estudio. Asimismo, estas convenciones están cargadas con la perspectiva dominante del pensamiento binario acorde con la circunstancia, como, por ejemplo: masculina y científica.";
  subtitulo = "Visión Fragmentada";
  parrafo16 = "La fragmentación se entenderá según el planteamiento de Bohm y Peat “cuando se intenta imponer divisiones de manera arbitraria, sin ninguna consideración por un contexto más amplio, incluso hasta el punto de ignorar conexiones esenciales con el resto del mundo” (2007, p. 57).";
  parrafo17 = "Capra (1992) recalca la impotencia de los especialistas ante los problemas, como, por ejemplo: el oncólogo no puede determinar las causas del cáncer; o en educación, seguir utilizando el modelo educativo prusiano con actividades de aprendizaje como clases magistrales, leer, escuchar, escribir y una evaluación sumativa de un conocimiento declarativo (Díaz, 2006) con contenido descontextualizado sin relevancia o motivación personal (Dale, 1946). Este modelo no se ajusta a los cambios vertiginosos, como la tecnología y las recientes exigencias educativas, para las actividades laborales de la economía en la sociedad actual. Se pierde de vista las conexiones “ocultas”.";
  parrafo18 = "Una metodología fragmentada obtiene una percepción limitada de la realidad. Esta se caracteriza según la disciplina y el pensamiento racional. Este último se determina por ser lineal, fijo y analítico encargado de diferenciar, medir, catalogar y por consiguiente fragmentar.";
  subtitulo2 = "Principios Fragmentarios";
  parrafo19 = "Se preconfigura la investigación con una concepción de la realidad, según la aproximación metodológica: cuantitativa, cualitativa, mixta. Pensar en esos términos es contribuir a la visión fragmentaria de la realidad y legitimar la tradición del pensamiento occidentalizado eurocéntrico. En un principio, el conocimiento es abstracto, objetivo, cuantitativo, general, ideal y masculino. Al final de cuentas, lo cuantitativo y lo cualitativo es un dualismo histórico que fundamenta la racionalidad, el primer polo considerado como superior dentro del modelo totalizador (Sousa, 2003) que se ha modificado drásticamente (Anadón, 2007).";
  parrafo20 = "Con respecto a la característica masculina del conocimiento, en el año 2007, varias compañeras universitarias instalaron el debate que el sujeto del conocimiento era el hombre y representaba a la humanidad. A partir de ahí, puse más atención a los textos para identificar quien era el sujeto en las oraciones, efectivamente era cierto. En la actualidad, no es tan obvio como antes. Aun cuando, se puede encontrar el sujeto en su forma masculina. El lenguaje importa, y por eso se sustituyó el sujeto de conocimiento del hombre a un lenguaje inclusivo.";
  parrafo21 = "Además, el medio escrito encierra las limitaciones para comunicar otras lógicas, tal como ocurre con el pensamiento complejo. Debido que se instalan viejas prácticas con palabras, o paradigmas, o teorías de moda en el ámbito académico (Toro y Parra, 2010) para interpretar la realidad, cuando la única variación son los conceptos o el marco de referencia.  Es decir, cambios de forma y no de fondo. Dicho fenómeno ocurre con palabras como: el pensamiento complejo, decolonialidad, interdisciplinariedad, transdisciplinariedad, diversidad, queer, teatro del oprimido, las epistemologías del sur, género, multiculturalidad, bullying, etc. No obstante, se requiere analizar si las palabras corresponden a las acciones o si solo es para obtener prestigio al incorporar lo “diferente” como una estrategia de legitimación (Curiel, 2007) o si las palabras implementadas no son suficientes para representar la realidad.";
  parrafo22 = "Por lo tanto, el conocimiento se expresa por medio de un lenguaje con la necesidad que debe de ser replicable. Por esa razón, se produce desde el punto cero para eliminar las particularidades (Grosfoguel, 2013). Sin duda, el conocimiento es una forma de poder porque traza una línea para determinar los criterios de superioridad e inferioridad en las formas de conocer (Grosfoguel, 2006). Ahora bien, cuando se erradican esas particularidades. El lenguaje “objetivo” desdobla a las personas investigadoras, lo cual lleva a no asumir responsabilidades y presentar un posicionamiento ante la realidad (Haraway, 1995). Además, esto puede generar un tipo de extractivismo cognitivo (Simpson y Klein, 2017).";
  parrafo23 = "De ahí que el uso del lenguaje para comunicar los resultados se convierte en un asunto ético, por lo que, se requiere desarrollar alternativas al lenguaje objetivo y principios fundamentalistas en la investigación para superar la fragmentación, y ampliar e integrar otras formas de comunicación distintas al escrito y verbal, en la cual, las personas que participan de la investigación se apropien de esos resultados y de la experiencia investigativa, igualmente se genere aprendizaje.";
  subtitulo3 = "Privilegios Epistémicos de la Persona que Investiga";
  parrafo24 = "En la lógica de la investigación social se parte de una problematización, entendida como la capacidad de construir, donde se relaciona un problema en una disciplina con los supuestos desde la postura de la persona investigadora. Como muestra, Bernal (2010), Ander-Egg (2011), Sautu et al. (2005), Hernández et al. (2014), Gómez y Alzate (2010) y Toro y Parra (2010) señalan que la persona investigadora decide, elige, toma decisiones y determina la construcción de la problemática y los contenidos en los elementos técnicos/prácticos para demostrar calidad con un estructura coherente, fundamentación teórica y rigurosidad metodológica. En consecuencia, al trabajo se le dará la respectiva seriedad y rigurosidad. Esto le dará prestigio a la persona investigadora (Toro y Parra, 2010).";
  parrafo25 = "Aunque, cada persona tiene principios y creencias que establece el modo de entender y comprender la realidad a su vez, se refleja en el texto del informe de investigación. Entonces, cumplen el doble papel de sujeto iniciador y productor de la investigación. Es decir, la persona investigadora decide qué es lo que le interesa resaltar, y, tanto formular la concepción de la problemática y el fundamento teórico, como encargado de seleccionar o rechazar los datos significativos (Morin, 2005). El fundamento teórico tiene la función de ser el marco para analizar los resultados.";
  parrafo26 = "Sin embargo, la intencionalidad o finalidad en la propuesta, como los objetivos, no son garantía que se cumplan los resultados esperados o la perspectiva analítica seleccionada con el aprendizaje (Lave y Wenger, 1991) ni mucho menos en la investigación. Al mismo tiempo, “la armonización de los objetivos, la teoría, los datos y el método de investigación tampoco garantizan buenas prácticas” (Poteete et al., 2012, p. 38). En conclusión, la persona investigadora tiene el privilegio epistemológico de etiquetar a otras personas desde un sistema de valores personales y criterios profesionales o institucionales.";
  parrafo27 = "En síntesis, todos los anteriores puntos representan condiciones previas que preconfiguran la investigación de alguna medida. Si no se identifica antes de realizar la investigación conlleva a repetir patrones sin ni siquiera plantearse la duda razonable o tratar de justificar si proceder o no de acuerdo a cada caso.";
  parrafo28 = "Tampoco se puede creer que estas condiciones previas son fáciles de llevar a la práctica de manera automática solo por el hecho de dedicar algunas frases en la investigación. Pero resulta más interesante trascender de la simple critica teórica con alternativas. El problema a continuación tiene muchas formas para resolver, lo que influye son las condiciones previas que fundamenta al problema o premisa de trabajo y el posicionamiento personal con la manera de abordaje que depende de cada persona.";
  subtitulo4 = "Componente Educativo";
  negrita= "¿Cuál es la Mejor Manera de Aprender en este Trabajo?";
  parrafo29 =  "Los argumentos que refiere a la eficacia de las enseñanzas en el sistema escolar reproducida en otros espacios educativos son: una enseñanza replicable independiente del contexto y las particularidades de las personas con objetivos y contenidos establecidos a priori, la utilización de técnicas didácticas para trabajar con grupos numerosos que depende del contexto institucional y promueve un conocimiento declarativo .";
  parrafo30 = "En este sentido, Díaz (2006) indica que las enseñanzas en el sistema escolar se utilizan en la enseñanza universitaria. Tal como ocurre:";
  parrafo31 = "en muchos contextos educativos todavía predomina una enseñanza basada en conferencias o cátedra magistral (el denominado lecturing) con grupos numerosos de alumnos, y que la forma de evaluación principal aún es la sumativa y formal, mediante exámenes escritos de selección de opciones que exploran conocimiento declarativo (Díaz, 2006, p. XIV).";
  subsub = "Cuestionamientos Personales sobre la Enseñanza";
  parrafo32 = "El conocimiento general  vinculado a representaciones abstractas con la descontextualización parcial o total es la principal manera de formular material pedagógico. No obstante, este tipo de conocimiento no tiene sentido a menos que se demuestre su relación con una situación. Además, el conocimiento general tiene una posición de privilegio con respecto a otras formas de conocimiento. Esas formas de conocimiento pueden ser más eficaz para transmitir una idea como las narraciones.";
  parrafo33 = "O cómo las personas que en algún momento de la vida estudió y adquirió conocimiento declarativo y se convirtió en inerte: algoritmos, rutinas y definiciones descontextualizadas (Lave y Wenger, 1991).  Una pregunta directa o planteamientos similares a la explicación o al texto se reproducen en circunstancias específicas y (Penzo et al., 2010), por lo tanto, no se pueden usar en el mundo en que se vive. Sería interesante preguntar a las personas que asistieron a la escuela y el colegio, para averiguar que aprendieron de cada materia.";
  parrafo34 = "Lo anterior provoco cuestionarme el usar esa forma de enseñanza. Por esta razón, decidí enfocarme en el aprendizaje, especialmente el cotidiano e independiente de la actividad educativa, el contexto y/o si haya intencionalidad o no. En palabras de Lave y Wenger (1991), el aprendizaje no solo sucede por medio de una enseñanza intencional. Por ejemplo, hay mayor oportunidad de aprendizaje en la práctica, más que en una relación asimétrica el profesorado y el estudiantado.";
  parrafo35 = "De ahí que, el aprendizaje es complejo, varía en cada persona y ocurre a diario.  Sobre todo, proponer el aprendizaje como un intento colectivo de explorar –al tema con - sus relaciones concretas y sus posibles interconexiones. Desde entonces, las actividades de aprendizaje son acciones de cualquier índole para construir colectivamente y aprender individualmente.";
  negrita2 = "Cómo Diseñar la Situación de Aprendizaje"; 
  parrafo36 = "Existen muchas formas de aprender y muchas otras de trabajar con el aprendizaje que dependen de las personas que conforma el grupo de trabajo en un tiempo y lugar determinado y de la persona encargada de planear o facilitadora del proceso educativo. Tampoco importa la selección nominal de la perspectiva teórica-metodológica ni las técnicas, si se reproduce violencia epistémica para obedecer las reglas impuestas por la academia o relaciones decoloniales de poder.";
  parrafo37 = "Aunque ninguna de las técnicas garantiza escaparse de lo anterior. Todo depende de la interacción en el campo, indiferentemente que se llame trabajo de campo o espacio educativo. La técnica, sea clásica o novedosa, solo se puede determinar con el tipo de interacción que se pretende realizar en el trabajo. Además, hay que seleccionar una opción que permita trabajar de manera colectiva con el conocimiento cotidiano y común.";
  parrafo38 = "Entre las opciones disponibles, el teatro representa una manera interesante de trabajar colectivamente con las personas. Esto depende de cómo se utiliza, así como de la aplicación de otros complementos dentro del mismo proceso para así sobrellevar las vicisitudes antes mencionadas. Con el tiempo, esta selección de los ejercicios teatrales como pieza fundamental de la propuesta puede variar. Pero es la selección acorde al acervo actual y la experiencia de usar la propuesta, lo que deja el aprendizaje necesario para continuar o replantearse el alcance de las posibilidades de los ejercicios teatrales en mis procesos educativos futuros como profesional.";
  titulo2 = "Problema o Premisa de Trabajo";
  parrafo39 = "Según Puentes (2014) señala que gran parte de los escritos e investigaciones de la Red Modernidad-Colonialidad se enfocan en reflexiones teóricas y no plantean cuestiones metodológicas. De la misma forma, esta situación es común dentro del conjunto de ciencias sociales con la utilización predominante de técnicas como la entrevista, los círculos de discusión, la encuesta y la observación. Este vacío aporta al cuestionamiento: si es posible de tener un marco de investigación diferente al actual, visto como deuda latente en la investigación social por:";
  cita = "(re)conocer aspectos de la realidad vivida y percibida, mediante sensaciones y emociones. Bailar, degustar, pintar, actuar, entre otras, son formas del sentir, con contenidos tan válidos como la palabra en tanto canal del pensamiento. Se propone poner un freno a lo estrictamente racional para que puedan aparecer otras formas de conocer y conocerse, de pensar y pensarse, de sentir y sentirse, con uno y con los otros (Scribano, 2016, p. 11).";
  parrafo40 = "En síntesis, el pensamiento complejo ha promovido cambios en las maneras de pensar la investigación, pero hay un desfase con las prácticas y metodologías ampliamente aceptadas por muchos espacios académicos. Pues, el reto en este trabajo es diseñar una propuesta metodológica desde los aportes de feministas y decoloniales para centrarse en el aprendizaje que se genera cuando se reflexiona sobre temas complejos que dependen de las subjetividades.";
  parrafo41 = "Se dificulta la utilización de la perspectiva compleja en la investigación porque formula muchos aportes a nivel abstracto o teórico. No obstante, proporciona la principal orientación de arriesgarse a utilizar las herramientas que permitan recopilar las subjetividades a pesar de las incertidumbres en el proceso. Estas incertidumbres se pueden generar al dejar de controlar el flujo de trabajo con dinámicas ampliamente utilizadas por las personas de la comunidad académica.";
  parrafo42 = "Además, no se niega la influencia del sistema educativo, que propicia y predomina en la enseñanza basada en conferencia magistral con grupos numerosos a partir de un texto como material de aprendizaje. Este texto de aprendizaje cumple una doble función: preparar la conferencia y servir como el material base de la evaluación sumativa con exámenes escritos, el cual explora el conocimiento declarativo mediante preguntas directas y específicas en el texto de manera literal. Este tipo de conocimiento que no se usa y se vuelve inerte.";
  parrafo43 = "Sin embargo, es importante resaltar que el aprendizaje es constante y cotidiano. Lo cotidiano en el aprendizaje implica que no hay un lugar o espacio exclusivo, ni actividad, evaluación o finalidad que garantice que suceda el mismo. Pero es el aprendizaje lo más importante en este trabajo.";
  parrafo44 = "Por lo tanto, este va ser el primer criterio para cambiar cualquier tópico, formalismo o precepto durante la formulación de la propuesta en este acercamiento metodológico. Tanto en la investigación como en el teatro, los cánones o las tradiciones de las mismas pasan a un segundo grado de importancia. Si en procura del aprendizaje se requiere modificar algún aspecto de las mismas, se realizará. Esto puede generar incertidumbre por salir de la zona de confort, al aferrarse a la comodidad y la seguridad en la infraestructura subliminal de las ideas tácitas. Mas que las seguridades, las certezas o “seriedad” basada en la verdad y los hechos, es determinar si se puede crear creativamente (Bohm y Peat, 2007) para promover el aprendizaje al momento de investigar.";
  titulo3 = "Objetivo General";
  parrafo45 = "Proponer una metodología para priorizar los aprendizajes que se generan cuando se reflexiona sobre temas complejos.";
  subtitulo5 ="Objetivos Específicos";
  itemlista = "Analizar componentes teórico-prácticos de las estrategias metodológicas usadas por expertas en procesos de trabajos socioeducativos.";
  itemlista2 = "Construir una propuesta metodológica a partir de un tema, escenarios y las experiencias utilizando las historias como técnica.";
  itemlista3 = "Reflexionar sobre la propuesta metodológica utilizada en la investigación para mejorar la estrategia metodológica sobre temas complejos."




  constructor() { }

  ngOnInit() {
  }

}
