import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-trabajo-de-campo',
  templateUrl: './trabajo-de-campo.component.html',
  styleUrls: ['./trabajo-de-campo.component.css']
})
export class TrabajoDeCampoComponent implements OnInit {

  imagen = "./assets/img/trabajo de campo/línea de tiempo trabajo de campo.png";
  fuente = "Elaboración propia, 2020.";
  subtitulo = "Convocatoria";
  parrafo = "Tal como se indicó en la metodología, el día 13 setiembre del 2018 se realizó la convocatoria vía correo electrónico. El proyecto Somos como Somos cuenta con la dirección electrónica de las personas que participaron en las sesiones de fotografía. Se procedió a enviar la invitación a 21 personas por correo electrónico. No obstante, existía la preocupación, por parte de Marcia Silva, que las direcciones de correo fueran inválidas pues hay información que data de más de diez años. La manera para contrarrestar esta preocupación fue la utilización de Facebook para crear un grupo secreto e invitar a las personas en esa misma fecha. Este grupo estaba conformado por 23 miembros. Al final, se invitó un total de 44 personas, pero solo se contó con la presencia de 7 personas para la sesión inicial el 30 de setiembre del 2018. Lo anterior refuerza la preocupación de la desactualización en la información de las personas participantes en el proyecto.";
  subtitulo2 = "La Planificación de la Sesión Inicial";
  parrafo2 = "La planificación de la sesión inicial está compuesta por dos actividades: la plenaria y el caldeamiento, tal como se muestra en la tabla con el mismo nombre. En el caso de la plenaria se divide en dos partes. La primera parte consiste en una introducción general del proceso y la segunda parte refiere a la presentación del consentimiento informado. Durante la plenaria se respondería cualquier inquietud que surja. La actividad de caldeamiento sirve como una muestra de los ejercicios que se utilizarán en las sesiones posteriores a la recopilación de las historias. Estos ejercicios se seleccionaron acorde a los principios de Boal y las experiencias previas en las sesiones de Teatro del Oprimido para conformar la propuesta del trabajo.";
  tabulacion = "Tabla 4";
  titulotabla = "Planificación de la Sesión Inicial";
  planificaInic = [
    {actividad:"Plenaria",objetivos:["Informar en que consiste el proyecto de TFG","Contestar las inquietudes."], asuntos:["Definir el término de historia como insumo para el material de aprendizaje","Definir varios aspectos del consentimiento informado","Cuaderno de campo: En qué consiste. Variación del binomio fantástico. Propuesta digital","Determinar la cantidad de secciones de trabajo","Registro audiovisual con cámaras: vídeos y fotos","Retroalimentación: No quiero un monólogo exclusivo. Grupo secreto de Facebook. Página Web (Duarte y otro autor más)"], tiempo:"20 minutos"},
    {actividad:"Caldeamiento",objetivos:["Estimular las capacidades corporales."], tecnicas:["Cruz y círculo","Caminata por el espacio, como si…","Carrera en cámara lenta","Equilibro","Espejo","Respiración diafragmática","Técnicas de respiración con globo","Ejercitación de labios usando trompetillas","Técnica de gesticulación usando BUE","Venta de cosas absurdas","Dramatización (dependiendo de los resultados de la plenaria)"],materiales:["-","-","-","-","-","-","1 globo número 4 por persona","-","-","2 Hojas de papel tamaño carta y 1 lapicero por personas","-"], tiempo:"40 minutos"},
    {actividad:"Continuación con la plenaria",objetivos:["Explicación del consentimiento informado. Contestar las inquietudes."], tecnicas:["-"],materiales:["Consentimiento informado"], tiempo:"30 minutos"}
  ];
  fuente2 = "Elaboración propia, 2020.";
  subtitulo3 = "La Sesión Inicial, 30 de Setiembre del 2018";
  parrafo3 = "Con la participación de estas 7 personas se continuó con la sesión inicial, tal como se estipuló en la metodología de este trabajo. Esta sesión consistía en un acercamiento inicial para explicar aspectos generales del Trabajo Final de Graduación (TFG): la presentación de la persona encargada de formular TFG a las personas participantes, informar en que consiste el proyecto de TFG y la participación de cada persona en la misma, recopilación del correo electrónico como medio de comunicación y responder cualquier duda que surja en el momento.";
  parrafo4 = "La misma tuvo una duración de 2 horas y solo se desarrolló las actividades de la plenaria. Se consideraron los aspectos generales y tomar la decisión de continuar o no hasta la firma del consentimiento como un indicio para continuar apoyando al TFG.";
  parrafo5 = "En síntesis, la sesión era de carácter informativo y tenía como objetivo asignar la tarea de seleccionar el material que se quería contar y enviar por correo las historias. De estas 7 personas, 5 personas firmaron el consentimiento y en teoría continuaron su participación, y 2 personas pidieron más tiempo para leer el consentimiento y determinar si continúan su participación o no.";
  subtitulo4 = "Parte 1: Entre Sesiones en Octubre del 2018";
  parrafo6 = "No voy a negar que al principio consideraba a la tecnología como una ventaja. No obstante, esto cambió con el transcurso del trabajo de campo, cuando intenté comunicarme por correo electrónico con las personas para acordar una próxima sesión y no tuve respuesta. El correo electrónico no era el medio de comunicación más práctico para las personas participantes, solo era el medio ideal para mí. Al fin de cuentas, el medio más práctico para las personas participantes resulto ser el WhatsApp.";
  parrafo7 = "Sin embargo, existe el caso de 2 personas que firmaron el consentimiento y se contaba con el número de WhatsApp, simplemente ya no contestaron más ni si quiera un mensaje de cortesía para indicar que ya no iban a continuar ayudando con el TFG.";
  parrafo8 = "Por lo tanto, el número de consentimientos firmados se redujo a 3, acorde al número de personas que continuaron y a la espera de la respuesta de las 2 personas que faltaban. Cuando me comuniqué con esas 2 personas que faltaban me indican que solo una persona iba a seguir ayudándome con el trabajo de campo.";
  parrafo9 = "Además, se hizo un primer intento de exponer la idea a personas que mostraron algún interés de participar. Me comuniqué con ellas para explicar en qué consistía el TFG en una primera instancia por WhatsApp, si le interesaba la idea, se procedía a una conversación telefónica. De esas personas, solo una persona mostró interés, pero al final desistió de participar por falta de tiempo.";
  parrafo10 = "Después de identificar el medio más efectivo para comunicar la información del TFG, apareció el inconveniente que las personas no tenían tiempo para realizar la recopilación de sus propias historias ni el tiempo para reunirse de nuevo.";
  parrafo11 = "Un inconveniente advertido por Marcia Silva que los últimos tres meses del año se complicaba realizar convocatorias. Pero lo que más me intranquilizaba era que las personas que continuaban no enviaron las historias por correo. Si las historias son la materia prima de este trabajo, vale la pena invertir más tiempo en la recopilación de las mismas.";
  parrafo12 = "Entonces, me planté la necesidad de hacer una sesión específicamente para recopilar las ideas de las historias y percibir si se puede continuar con el trabajo de campo, porque los mensajes por WhatsApp eran escasos y alentadores para continuar. Sin embargo, no enviaban sus historias y necesitaban más tiempo del acordado en la sesión inicial. En ese momento, sentía que se imponía una realidad diferente a lo que comunicaban las personas participantes. Fue hasta que se pudo convenir en la fecha de 3 de noviembre del 2018 para esta sesión de recopilación. No obstante, no se pudo contar con todas las personas, solo falto 1 de las 4 personas. Al inicio pensé que esta ausencia no afectaba el proceso.";
  subtitulo5 = "Sesión de Recopilación, 3 de Noviembre del 2018";
  parrafo13 = "Al ser las historias el insumo fundamental de la propuesta. El objetivo principal era compartir y conversar las historias que las personas traían o desarrollarlas si era necesario. Si el espacio para compartir las historias era de manera expedita, se podría aplicar el caldeamiento planificado para la sesión inicial, que no se utilizó.";
  subsubtitulo = "Inconvenientes con las Historias";
  parrafo14 = "La principal razón era la falta de tiempo para desarrollar una estructura de la historia, porque si tenían seleccionado el recuerdo que querían contar. Además, detecté una razón secundaria por la indicación de utilizar las historias. Este término de historia era ambiguo para las personas participantes, en el sentido que la indicación era compleja y que englobaba todas las posibles respuestas de cada persona que colaboró en el trabajo. Esta característica fue algo buscado e intencional desde el inicio de TFG.";
  parrafo15 = "Por ese motivo, se pretendió no profundizar con detalles no pedidos por las personas ni dar ejemplos, porque eso podía uniformar o normalizar y condicionar en mis términos a las personas para realizar el ejercicio de reflexionar de forma sentida y particular sobre el cuerpo y sus vivencias, que era la finalidad de esta indicación. En este sentido, me hace cuestionar el alcance de la sesión inicial, pues no use 2 técnicas para trabajar en la construcción de historias y la actividad de caldeamiento, al pensar que se resolvió las dudas de las personas y parecían comprender la dinámica de utilizar las historias. Aunque al final el material recolectado corresponde a la expectativa de la variedad en el contenido de las historias y la forma de registrarlas. Se debe en gran parte a la indicación de utilizar a las historias e investigar a partir del tema como la figura central.";
  subsubtitulo2 = "Resonancia";
  parrafo16 = "es el efecto de generar movimiento interno en las personas que escuchan las historias que se compartió en una sesión, no siempre ni a todas las personas le sucede igual. Este efecto que mencionan los libros de Boal y Nancy Banard en la Multiplicación Dramática. Pero no se entiende hasta que no se experimenta y se vuelve vital darle tiempo y espacio en las sesiones para compartir las historias con las personas participantes, sin repeticiones innecesarias o no sentidas, para eso se debe trabajar con el grupo completo y sin incorporaciones esporádicas.";
  parrafo17 = "Entre las historias de la sesión, me gustó la idea de “Luna de San Jorge” para crear su propia caja de herramientas y la historia de Antonia. Esta última me resonó al producirme sensaciones y recuerdos en ese momento. Al ser una historia compuesta por escenas retrospectivas de esas situaciones cotidianas que produce la sensación de dejar de ser uno mismo por otra persona. Pero que lo aceptaba como algo normal. Ahora me daba cuenta que lo invisibilizaba en cierto grado y lo hacía apropósito, lo cual me fastidió. Inicialmente, se grabó el audio como una forma de registrar. Posteriormente, se acordó con Antonia no usar el audio en el TFG, porque exponía detalles personales en un documento de consulta pública. El audio era opuesto al primer principio en el encuadre: lo importante son las personas.";
  subtitulo6 = "Parte 2: Entre Sesiones, desde Noviembre del 2018 hasta Enero 2019";
  parrafo18 = "La sesión de trabajo 3 noviembre dejó la sensación que las personas participantes tienen la disposición para aportar las historias. Aunque no tenían el tiempo para sentarse y recopilar sus historias. Por esa razón se dio este periodo. La otra razón fue que los meses de noviembre y diciembre se complicaban por los múltiples compromisos personales de fin y principio de año. También, les recordé el uso del correo electrónico: detrasdelarbol@hotmail.com durante los meses de noviembre, diciembre y enero. Las personas participantes podían utilizar el correo para alguna de las siguientes dos situaciones: enviar el material recopilado y/o notificar que no van a continuar con el proceso.";
  parrafo19 = "La realidad fue otra con respecto al material recopilado durante este periodo. Solo se recibió dos correos con el material respectivo a dos personas participantes. Luego, a estas dos personas les recomendé realizar el ejercicio de volver a leer el material, si durante la lectura le aflora un recuerdo o una vivencia en concreto y quiere contarlo. Puede agregar ese recuerdo a la historia. De lo contrario, ya estaría terminado su material. Sobre todo, que lo importante es si cada persona está a gusto con el material como para publicarlo en el TFG. Las demás personas del grupo siguen sin informar el proceso de su material o si van a continuar la participación en el trabajo. Lo único que quedaba era esperar a que llevaran el material a la próxima sesión el 9 de febrero del 2019. Fecha que se confirmó hasta 28 de enero del 2019, aunque se intentaba concretar una fecha desde noviembre del año anterior.";
  subtitulo7 = "Mes de Enero 2019";
  parrafo20 = "En esta oportunidad se intentó incorporar a 4 personas más al TFG, a pesar que estaba conforme con el grupo. No obstante, seguí la recomendación de Marcia Silva de intentar invitar más personas, aprovechando el periodo de inactividad en el trabajo de campo. Ella se encargó de realizar una breve presentación del TFG y de preguntarle si tenían algún interés.";
  parrafo21 = "Ya con la respuesta afirmativa de estas 3 personas, procedí a contactarme con ellas, inicialmente por Facebook, para la presentación de TFG y para responder cualquier duda, si fuera necesario de conversar más sobre el TFG vía telefónica o cara a cara. Con una persona que me pidió más información se volvió imposible comunicarse para darle la misma. Otra persona me pidió más información y hasta conversamos cara a cara para ampliar y responder cualquier duda. Aunque esta indicó que le interesaba y pretendía participar, dejó de responderme los mensajes. La tercera persona se contactó por Facebook, se contestó las dudas que tenía y ella aportó su historia. La cuarta persona se presentó el día de la sesión de recopilación con el grupo completo, se intentó explicar durante el transcurso de la sesión y observó la dinámica del trabajo de campo. Tiempo después, esta persona se comunicó para informar que no podía ayudar con el TFG.";
  subtitulo8 = "Inconveniente con la Red Social para la Retroalimentación";
  parrafo22 = "La elección de red social fue un aspecto importante para las personas participantes en la primera sesión. La preocupación radicaba en el nivel de confidencialidad para los datos suministrados dentro del proceso investigativo con una aplicación de terceros como Facebook.";
  parrafo23 = "Esta preocupación me hizo revisar el procedimiento establecido en el 2017 con la Api Graph de Facebook en la versión 2.6 que brindaba la información de forma más descriptiva y similar a la estructura de datos requerida: JSON, que permitía tener el contexto de los elementos iniciales con la persona autora y las reacciones de cada persona en la red social. No obstante, la versión 3.1 de la API recopila la información de forma desconectada entre el contexto, el elemento inicial y las reacciones al separar la autoría de los mismos.";
  parrafo24 = "En síntesis, la versión 3.1 de la API pierde la ventaja para la recolección virtual de la retroalimentación. También, existen escándalos por la filtración de datos pertinentes a las cuentas de los usuarios, que incumple la política de privacidad tanto de Facebook como de Google+. Por estas razones, no se puede garantizar la información que se recolecta con las redes sociales comerciales de terceros y no existe una red social confiable para fines investigativos al desconocer el alcance de la información recolectada. Al final, esto representa un inconveniente a tener en cuenta y dar a conocer a las personas participantes como un riesgo latente de usar una red social.";
  subtitulo9 = "Sesión de Recopilación con Grupo Completo 9 de Febrero del 2019";
  parrafo25 = "En esta segunda sesión me di cuenta que es fundamental la participación de las personas en todas las sesiones relacionadas con la recopilación de las historias para compartir y conformar un conocimiento base en el grupo.";
  parrafo26 = "Las personas cambiaron el modo de contar sus historias. Por ejemplo, Antonia cambio el qué, y el cómo comunicó su historia de manera comprimida, objetiva y sin detalles, porque el tiempo ayuda a sentir su historia de otra forma y la desconfianza de incorporaciones abruptas de otras personas. En el caso de “Luna de San Jorge”, la persona desarrolló la idea de crear su caja de herramientas, aunque en realidad era la recopilación de material significativo que ella había elaborado anteriormente. Este material cuenta con un relato descriptivo y un tono cálido que enlaza el material en la historia de Luna de San Jorge.";
  parrafo27 = "En estos dos casos, es cierto que no hay un registro de las historias hasta la fecha, pero se requiere más tiempo para que estas dos personas puedan desarrollar su propio material de las historias. Al final lo que importa es que las personas estén a gusto con su material y las representen.";
  parrafo28 = "Por otro lado, el caso de la Medusa, Georgeanella y Nigromante no necesitaron mucho tiempo y si encontraron el material que los representaban de inmediato. Ahora bien, la variedad del material manifiesta la dificultad para unir intenciones: las historias son para que cada persona reflexione sobre el tema y crean su propio material didáctico en la investigación.";
  subtitulo10 = "Parte 3: Entre Sesiones, Desde Febrero Hasta Abril de 2019";
  parrafo29 = "Se dio el lapso de 22 días para que desarrollaran su material las personas que faltaban. Se procedió a proponer posibles fechas hasta que se concretó veinte días después la fecha del 20 de abril del 2019 para la siguiente sesión de trabajo. En este periodo se esperaba poder recolectar las historias por correo electrónico.";
  parrafo30 = "No obstante, esto no se logró cumplir. Por esta razón, se decidió concluir el trabajo de campo con la recopilación de las historias en la próxima sesión, es decir, la propuesta solo se pudo aplicar hasta el segundo escenario, según el diagrama de flujo. No se obtuvo la participación requerida en un periodo de seis meses para completar la propuesta.";
  subtitulo11 = "Sesión de Recopilación Final, 20 de Abril del 2019";
  parrafo31 = " A pesar de la confirmación de todas las personas., ese día solo se presentaron dos. Las demás cancelaron ese mismo día de manera repentina y sin previo aviso. Así que, otra vez, no se pudo contar con el grupo de trabajo completo. Ese fue un inconveniente en el trabajo de campo.";
  parrafo32 = "No se pudo generar un conocimiento común entre las personas que participaron. Solo se pudo recolectar y presentar la historia de “Luna de San Jorge: la caja de herramientas” y la historia de Aniretake. Quedo pendiente de recopilar la historia de Antonia. Ella faltó a la sesión ni pudo completar un material que la representara para esta fecha, no pudo enviar la historia. Ella prometió enviar su material en una fecha posterior. En esta sesión de recopilación final se agradeció por la participación de las personas en este proceso. "
  subtitulo12 = "Cierre del Trabajo de Campo: Recepción de la Última historia."
  parrafo33 = "Hasta el 22 de mayo del 2019 recibí el correo de Antonia con su historia. Con esta historia se concluye el trabajo de campo de este TFG."

  
 
  
  





  constructor() { }

  ngOnInit() {
  }

}
